### ISSUE TITLE
Active AF won't change frequency in xdr-gtk 

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#102]
when AF is on and connection to xdr-gtk is established the frequency won't change in xdr-gtk

![IMG_20230718_190345](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/2f912726-e1dc-4029-927c-97b8ca5fd639)

In this screenshot frequency changed from 104.9 to 107.4 according to received AF, but the frequency on xdr-gtk stays the same.

**Comment by PE5PVB** [comment]
Can you test with the latest beta from today and report back?

**Comment by andimik** [comment]
Yes, fixed.
