### ISSUE TITLE
RDS Errors are green when RDS got lost

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#125]
![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/bfa3d492-0423-4f40-9554-43f680d6b5da)

When RDS signal got lost, the 4 RDS error dots still show green instead of red.

**Comment by andimik** [comment]
Another picture shows first in green, the rest in red.

![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/bf6b3469-e519-451f-abac-2c16bd19a23f)

Hint: the PI was garbage in this case due to bad reception quality.

**Comment by PE5PVB** [comment]
Yes, they were frozen on RDS lost. So last state was shown. But you are right, on no RDS all should be error, so now they will be red on RDS loss.

Fixed
