### ISSUE TITLE
RT+ shows first character when Raw Data are 0

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#126]
Described in https://discord.com/channels/1053804249651359765/1053804250276298895/1132563377839943791

When RT+ has the following flags:

```
RT Plus:
Tag 1    = Tag 1 = 
Tag 2    = Tag 2 = 
Raw Data = 0,0,0,0,0,0

RT History:
20:26:33 VIALE SARCA 223 - MILANO    
```

then the RT+ will show the first character from the RT, in this case `V` from `VIALE`

![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/f0202ac8-fff6-4343-8571-cb7f51966024)

**Comment by PE5PVB** [comment]
Yes this is known. RT+ is currently in RAW mode. running and toggle bit aren't implemented yet. Even as tagging.

**Comment by PE5PVB** [comment]
RT+ is now completely updated including tags. Please check.
