### ISSUE TITLE
Empty AF does not show text 87

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#128]
Other than EON or RT+, empty AF will not tell, that there is no AF. 

For example, this station has no AF:
http://andimik.bplaced.net/sendinfo.php?id=256

![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/4994899f-931f-4ecc-a6cd-dbf2a7418bc1)

Expectation: 
Write the text defined in 87.

https://github.com/PE5PVB/TEF6686_ESP32/blob/921b04170a72e9fe7cae6180f5d3833f370c699d/src/language.h#L91

Could you check
https://github.com/PE5PVB/TEF6686_ESP32/blob/921b04170a72e9fe7cae6180f5d3833f370c699d/TEF6686_ESP32.ino#L3239

**Comment by HyperDX** [comment]
I noticed that if the frequency that you are tuned into is broadcasted on AF list by radio station it somehow doesn't appear on AF list on the screen. Maybe this issue is related to it.

**Comment by andimik** [comment]
I don't think so. As there is no AF transmitted, the TEF cannot check that.

**Comment by HyperDX** [comment]
I've done a quick test. I broadcasted RDS on 87.7 MHz. At a first attempt empty AF list in RDS encoder settings.
TEF shows "No AF available". Second try I put 87.7 MHz on AF list in RDS encoder and AF list on TEF is blank as shown on the first screen.

**Comment by PE5PVB** [comment]
The transmitter frequencies will not be added to the AF list. I filtered that one.

**Comment by PE5PVB** [comment]
Ok. What is the actual problem? When the only AF is the current frequency, it will be filtered. When I check AF with transmitters which transmit multiple frequencies, I see no problems.

**Comment by PE5PVB** [comment]
The reason why it shows empty is because AF flag is there, but the only frequency in the AF list is it's own frequency, which is not shown.

**Comment by andimik** [comment]
Let me check in the next days. On my link you can see that AF is not used. Maybe the broadcaster has changed it in the meantime. 

I am aware that TEF won't show the received frequency. 

In my opinion it was **not** the case as I assumed that there are no AF transmitted at all at this station.

**Comment by HyperDX** [comment]
> Ok. What is the actual problem? When the only AF is the current frequency, it will be filtered. When I check AF with transmitters which transmit multiple frequencies, I see no problems.

I'd say it would be important for person who manages online RDS databases where they need to fill AF list. I think on the other hand for regular person it doesn't matter is it filtered or not.

**Comment by andimik** [comment]
Closed. The mentioned radio station has added its only frequency to AF in the meantime.
