### ISSUE TITLE
"Beep at band edge" menu shows signal level

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#13]
When you want to set "Beep at band edge" in the menu, then you can choose between On and Off, but you also see the current signal level strength in this menu item.

![IMG_20230610_013124](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/e6406aee-6ce3-4345-8438-d2ddc58e568f)

Tested with English, Nederlands and Deutsch.

**Comment by PE5PVB** [comment]
Fixed.
