### ISSUE TITLE
Missing sprites

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#130]
In this issue all missing sprites should be reported.

![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/8902590e-0b79-4531-bd96-dd4b4dfba424)
(at `M` from `MHz`)

**Comment by PE5PVB** [comment]
Can you show me your full screen when this happens. I haven't found a way to reproduce it.

**Comment by Mike86-CZE** [comment]
I manage to get this error when I switch between bands.  With OIRT, "M" is still OK at MHz, when switching to FM later, "M" is broken.

**Comment by Mike86-CZE** [comment]
https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/d0485693-b344-4d58-b6b6-0db545285d88

**Comment by PE5PVB** [comment]
Thanks. Fixed it.
