### ISSUE TITLE
Squelch shows double text

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#131]
The word `OFF` (in the pic it's the localized German word `AUS`) is in the background of the squelch value.

![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/e6517cf9-b4ae-4f0f-8664-7baf5af79fea)

This seems to happen when the squelch is changed during scanning.

**Comment by PE5PVB** [comment]
I was not able to reproduce it. Can you make a video where you reproduce this problem?

**Comment by MCelliotG** [comment]
In my opinion, the value should move to the same line as SQ: It causes issues in translations where the word for OFF is more than 3 characters.

**Comment by PE5PVB** [comment]
I have changed the alligment of the text, this will help. There is not enough space on the screen to do it in one line.

**Comment by PE5PVB** [comment]
Fixed
