### ISSUE TITLE
MEM places (are not band-related)

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#132]
Although the description changed from `FM` to `OIRT`, the MEM places are not related to each band. I know that this is a limitation, but the MEM position after the BAND is misunderstanding.

So a user will overwrite the MEM position 1 although he thinks, this is free.

Suggestions: the text for BAND and MEM place should not be displayed one after the other. See advanced RDS view.

![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/ab376f28-86ec-47ec-a558-b92a50b9c1d0)

**Comment by ohmytime** [comment]
In the next function ,I may add MEM Pages, I can change it's location.

**Comment by PE5PVB** [comment]
I changed the indicators from position, but what is the real question? Memory channels are currently designed to have a mix of all bands.

**Comment by Overland-DX** [comment]
I was wondering the same thing. But what is the plan in the future? Mix with all bands or separate them between each band? I'm super happy with it as it is, but I think it might be a little easier if the memory channels were split up into each band?

**Comment by andimik** [comment]
> but what is the real question? Memory channels are currently designed to have a mix of all bands.

It's a kind of usability. OIRT1 is the same as FM1...

**Comment by PE5PVB** [comment]
Yes, the plan was a global channellist. Please start a discussion about it in Discord, I never use memory channels, so ask others opinions.
