### ISSUE TITLE
Wrong calculation for SNR on OIRT

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#133]
My antenna cable was not properly connected, so I got these values

![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/f8c5064f-7b29-4269-8b61-161bab22572b)

Switching to FM the values were ok, so only OIRT affected.

BTW: Have not tried to get that behavior a second time.

**Comment by HyperDX** [comment]
Also this issue can be related to AM where SNR measurements make no sense

**Comment by ohmytime** [comment]
> Switching to FM the values were ok, so only OIRT affected.

Is the current frequency a real valid station? I tested with latest code , it works fine on OIRT band on any frequency.
Or you can press Rotary button + BW button to restore to factory .
Then have a try.

**Comment by ohmytime** [comment]
> Also this issue can be related to AM where SNR measurements make no sense

SNR not correct is an known issue. to be done.

**Comment by PE5PVB** [comment]
Signalstrength if -99.8dBuV is not possible. I've seen this behaviour before some time ago. It was caused by wrong data from the TEF chip. I've added a constrain between -20 and +120 dBuV for both AM and FM
