### ISSUE TITLE
Offset on OIRT frequencies

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#135]
@ohmytime 

Dear Kevin, the OIRT frequencies are wrong. There is an offset as the edges are not correct.

I've changed them to

```
#define FREQ_FM_OIRT_START         6590   // use values of 1/10 * kHz
#define FREQ_FM_OIRT_END           7400   // use values of 1/10 * kHz
```
And it works!

![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/62e3cc4f-7fb3-4458-8aa0-0dbd2db0e9ed)

Due to the new OIRT band implementation, there is no need to have a menu item for the FM lower edge in my opinion.

**Comment by ohmytime** [comment]
> I've changed them to
> 
> ```
> #define FREQ_FM_OIRT_START         6590   // use values of 1/10 * kHz
> #define FREQ_FM_OIRT_END           7400   // use values of 1/10 * kHz
> ```
> 
> And it works!
> 

Thank you for your feedback, you can submit a PR to change them directly.


> Due to the new OIRT band implementation, there is no need to have a menu item for the FM lower edge in my opinion.

Well, I think OIRT and FM can be different bands, because some users would hide OIRT and keep FM band.
So I think it is better to keep this function, so that they can customize FM band range.

**Comment by PE5PVB** [comment]
Changed in repository.

**Comment by MCelliotG** [comment]
FM lower edge should stay, just to cover 74 and up, in order to still include Japan FM.
