### ISSUE TITLE
Redrawing the frequency on AF screen

### ISSUE THREAD

**Issue by Mike86-CZE** [PE5PVB/TEF6686_ESP32#140]
On the AF screen does not completely redraw the previous frequency when changing to another frequency.

![20230727_110348~2](https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/0ed5bb39-bdb1-4973-91e4-b5b73afd869c)

**Comment by andimik** [comment]
AF is on?

**Comment by Mike86-CZE** [comment]
Yes, there was an automatic retune to a better frequency.

**Comment by PE5PVB** [comment]
AF should not happen when AF screen is shown. Fixed this and this will also prevent the behaviour. In future updates AF zapping will be possible, and you don't want AF to kick in.
