### ISSUE TITLE
The last characters of the AF list on the RDS screen are missing.

### ISSUE THREAD

**Issue by Mike86-CZE** [PE5PVB/TEF6686_ESP32#142]
On the advanced RDS screen, when the AF list is scrolled, the last few characters are not displayed.  For example, the last frequency in the list is "106.1", but only "10" is displayed. It happens often, but not always.

**Comment by andimik** [comment]
Can you post a screenshot?

**Comment by Mike86-CZE** [comment]
https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/c5989fca-3033-4218-864b-f1a25936964c

**Comment by PE5PVB** [comment]
It seems that the AF list is still expanding with new frequencies. This has effect on the ticker, because the end marker is based on the string length. Can you wait for a few minutes after tuning and check if the ticker then works correct?

**Comment by Mike86-CZE** [comment]
It keeps happening even after a few minutes.  The signal is good.

**Comment by Mike86-CZE** [comment]
Maybe it's happening because of the font.  It would be good to insert spaces after the AF list.

**Comment by PE5PVB** [comment]
I've added 5 extra spaces at the end of both AF and EON ticker.
