### ISSUE TITLE
when trying to enter the menu, it displays "not possible"

### ISSUE THREAD

**Issue by Mike86-CZE** [PE5PVB/TEF6686_ESP32#143]
Sometimes it won't allow me to enter the menu using the middle button and displays "not possible".  This has now happened to me twice in a short period of time.  I still don't know how to target this error.

**Comment by PE5PVB** [comment]
Did you connect XDRGTK?

**Comment by Mike86-CZE** [comment]
No.  USB or wifi not connected.

**Comment by PE5PVB** [comment]
That is strange, because only way this could happen is when XDRGTK was connected (before).

**Comment by Mike86-CZE** [comment]
I understand.  But I didn't try to connect at all during the session.  wifi is turned off.

**Comment by PE5PVB** [comment]
Maybe something was triggered over USB

**Comment by ohmytime** [comment]
Hello, you must hidden some bands. 
Try to enable them.

**Comment by andimik** [comment]
Maybe a reset helps here?

**Comment by Mike86-CZE** [comment]
The error seems to randomly occur after AF retuning.  I can't say more at the moment. Yesterday's release.

**Comment by Mike86-CZE** [comment]
Now this happened to me when saving a preset.  But I can't repeat it.

**Comment by andimik** [comment]
https://github.com/PE5PVB/TEF6686_ESP32/blob/cb31950de0c694efdd14714acb28a7a742f128f0/TEF6686_ESP32.ino#L1754-L1760

This is the only code where "Not possible" is displayed. It has to do with xdr-gtk via WiFi or USB.

**Comment by PE5PVB** [comment]
Correct, and this should only be called when XDRGTK connection is active. But the issuer said he had no WiFi or USB connected.

The only place where it's set to true in is comms.cpp, and only in specific situations. So I really have no idea.

**Comment by Mike86-CZE** [comment]
I haven't encountered this error in a long time.  I still don't know where the problem was.

**Comment by PE5PVB** [comment]
Possibly it was fixed during development ;-)
Let's close this one. Please re-open when it occurs again and describe what has been done during power on and the moment the problem occured.
