### ISSUE TITLE
WiFi icon broken resp. wrong sprites

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#156]
I wonder that nobody has reported already

![IMG_20230729_115302](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/c6c38749-4a5c-4791-a32d-59dfd8396952)
![IMG_20230729_115119](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/7440165f-a0f1-4cd6-a747-18687fba3f96)
![IMG_20230729_115059](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/d70620c1-047d-458d-a725-ffc0cbf48f2d)
![IMG_20230729_115019](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/98ff5803-c34d-456a-9d36-639873ba8f44)

**Comment by PE5PVB** [comment]
Fixed
