### ISSUE TITLE
RDS issue after retune in Stationlist

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#165]
If I (double)click on a frequency (can be the same of course) in Stationlist for Windows, TEF will retune to that frequency.

But then RDS is broken, no idea why. Group D seems to be working all the time, but groups A, B and C may be marked as red.

See pictures. Signal quality is excellent. 

I could reproduce it several times.

![IMG_20230730_122143](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/1911d894-d2a0-4c78-9553-c1c45ba28801)
![IMG_20230730_122042](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/4f342a31-986e-404c-ba0b-a0c4c6817871)

**Comment by PE5PVB** [comment]
Fixed.
