### ISSUE TITLE
Problems with "screen off" in the menu.

### ISSUE THREAD

**Issue by Overland-DX** [PE5PVB/TEF6686_ESP32#171]
When I have activated "Touch rotating", then "screen off = 3 sec" is set in the settings when I switch the screen off and on with the "band" button on the LW/MW/SW band.

for example:
if I set "Touch rotating = On" and "Screensaver = Off" then Exit and Store.
Go to a SW band and hold the band button to turn off the screen.
When I then press the band button once to turn on the screen, it turns off automatically after 3 sec.
I then go into the menu and see "Screensaver = 3 sec"

**Comment by ohmytime** [comment]
Touch rotating is designed to change the frequency with the screen off as much as possible, it needs to be used with screen saver ON, but some users don't know this.
For the convenience of use, when touch rotating is set On in the menu , screen saver will also be set to ON asynchronously, and the default setting is 3 sec.

Back to your question.
If you want to touch rotating and manually control the screen on and off at the same time. I think this is conflicting.
Please choose one from the two.

**Comment by Overland-DX** [comment]
I think it was a decent solution as it was in previous versions of v.2 beta.
This is new in the latest version. Previous versions of 2.0 Beta had this separated, so something has changed in the latest update.

**Comment by ohmytime** [comment]
Yes, I added this part in #163

**Comment by Overland-DX** [comment]
I understand. In these situations, it would have been nice to have an update log, so we don't have to send error messages about things that have changed.
