### ISSUE TITLE
PTYN color when it's N/A

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#188]
https://github.com/PE5PVB/TEF6686_ESP32/blob/fc14a4bc0fd95d8629a159b2e869a199f2cc758d/TEF6686_ESP32.ino#L2260-L2266

Can you print the word PTYN in white and N/A in yellow?

I know that the space is limited and the word PTNY might be skipped when it's not 0 (as far as I understood, because there is no station with PTYN here).

**Comment by PE5PVB** [comment]
It is a lot of work to do this. When PTYN is available the whole text PTYN N/A will be replaced by PTYN text.
