### ISSUE TITLE
RDS Block A error indicator

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#189]
The RDS block A error indicator is not working properly.

[VID_20230804_095819.webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/4cebe08c-17ec-4032-b3b6-2478e3ec1079)

**Comment by HyperDX** [comment]
It's interesting because I can't reproduce it myself. In my case A error block is working properly

**Comment by andimik** [comment]
Try tuning to a very weak station or using a bad antenna. I fear that rdsAerror is not set to false or true after retuning.

**Comment by MCelliotG** [comment]
I can't reproduce it either, I have many weak stations in my area.

**Comment by PE5PVB** [comment]
Fixed.

**Comment by andimik** [comment]
Wow, thanks Sjef!
