### ISSUE TITLE
Battery percentage on v1 useless

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#191]
On my original (Dutch) v1 TEF switching to *Battery options* -> *Show percentage* will show that anyway but break the layout.

Screenshots from English and German translation

![IMG_20230804_121723](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/ad842d78-c485-46e4-9aef-b4f8de99119b)
![IMG_20230804_121658](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/1a136a13-f943-4111-b816-7a8beab5b2e1)

**Comment by PE5PVB** [comment]
Fixed
