### ISSUE TITLE
Internal noise increased on latest firmware

### ISSUE THREAD

**Issue by DE1103DX** [PE5PVB/TEF6686_ESP32#196]
After flashing a recent firmware version, dated on Aug 3rd, overall noise levels significantly increased on numerous FM frequencies, most notably around 87.3-87.8, and as mentioned by other users on 101.8. As well as many frequencies below 87 MHz. On 87.45 two regularly received stations are badly interfered, this internally generated display noise was much weaker on the earlier firmware, dated around Jul 11 (released just after the AM signal level offset was included to the menu, several days before adding the advanbced FM AF lists). In addtition to that several weak FM signals mainly in the lower portion of the band around 91 MHz sounded slightly noisier (but not as serious as around 87 MHz). Perhaps this is caused by changed, altered clock frequencies, more data transfer between the chip and the display or something else related to the display? After downgrading to a older firmware version dated on Jul 15, noise levels on the lower FM band decreased, 87.8 and several other frequencies became usable (when the display switch off long press band button function was added, and before more AF list features were implemented). Besides this there are some performance issues on another post,

**Comment by PE5PVB** [comment]
Possibly caused by increased SPI frequency. I will slow it down a bit in the next beta release.
