### ISSUE TITLE
Slower performance, lagging on recent fimware

### ISSUE THREAD

**Issue by DE1103DX** [PE5PVB/TEF6686_ESP32#197]
After flashing a recent beta firmware version (Aug 3rd), navigating through the menu pages became noticeably slower, and loading the RDS AF listing requires at least twice as long, compared to a earlier firmware version (Jul 15). Overall performance seems to have worsened. After downgrading to the Jul 15 firmware, performance improved, menu pages and RDS AF lists are loading much quicker (similar to the Jul 11 firmware that was used before).

**Comment by ohmytime** [comment]
Yes, some adjustment was made to tftPrint method, and now I think is as quick as old firmware(Jul 11).

**Comment by PE5PVB** [comment]
I made some improvements on the font handling.
