### ISSUE TITLE
Only a minor issue; AM sensitivity, mainly on LW, decreased a little bit

### ISSUE THREAD

**Issue by DE1103DX** [PE5PVB/TEF6686_ESP32#198]
Upon flashing the Aug 3rd beta firmware version, using the very same settings as before, signal levels mainly on LW decreased a little bit, this was most apparent on 198 kHz BBC Radio 4. Around 5 dB less compared to the Jul 11 or 15 firmware versions. The AM display switch off (long press band button) feature is very useful, thanks for adding that to the firmware, it really reduces a lot of noise or display interference. On the currently installed Jul 15 firmware, 198 kHz BBC Radio 4 peaks at aound 70 dB or S=9+40 dB on a BNC connected telescopic whip (one of the strongest signals overall).

**Comment by PE5PVB** [comment]
There were no changes done affecting this.
