### ISSUE TITLE
White display (crash?)

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#200]
Sometimes on my original v1 TEF I have a white display and I need to reboot it.

I don't know if this is related to WiFi (as I'm currently testing a lot) of will show after a while.

![IMG_20230805_193329](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/23d110c0-0209-4ee2-a918-21d4b95e0923)

**Comment by ohmytime** [comment]
which firmware?

**Comment by andimik** [comment]
Latest of course

**Comment by ohmytime** [comment]
Can you show more details , under what conditions would cause reboot ?

**Comment by andimik** [comment]
I don't know. The power supply is plugged in, WiFi is on. Screensaver is off.

May happen after several seconds or many minutes.
Have not seen that in previous versions.

Up to now no chance to check if something was printed on the serial port.

**Comment by PE5PVB** [comment]
Do you use a seperate front pcb?

**Comment by andimik** [comment]
No, it is the original, without modification.

**Comment by PE5PVB** [comment]
Try add the 100n caps directly on the back of the rotary encoder.

**Comment by andimik** [comment]
I see, but I won't modify the hardware by myself. Just wanted to report it.

**Comment by PE5PVB** [comment]
We had this issue in the past, it was solved by adding 100n caps on CW and CCW pin directly on the rotary encoder.

**Comment by andimik** [comment]
Can you post a picture resp. a schematic?

**Comment by ohmytime** [comment]
On item "Wi-Fi active ", when it is set to ON, and then user press mode button not rotary button, it will cause reboot. we're working on this.

**Comment by andimik** [comment]
But what you describe is a simple reboot. Mine is a crash and freeze.

Let's see where the modifications has to be soldered.

**Comment by PE5PVB** [comment]
Correct. When this happens the display shows only white, no reboot. Problem was caused by interference on the 3v3 powerrail of the display
