### ISSUE TITLE
Adopt new RT-behaviour to advanced RDS-screen

### ISSUE THREAD

**Issue by lxsxl** [PE5PVB/TEF6686_ESP32#201]
The new RT-behaviour is excellent. Buffer, speed, A/B-switch, legibility are all quite fine.

This should be the same for RT/RT+ on advanced RDS-screen. And imho the max speed should also be used for AF and EON tickers.

**Comment by andimik** [comment]
AF and EON won't change, as long as you don't select another frequency.

**Comment by lxsxl** [comment]
Of course they won't change. For AF and EON only "the max speed" is meant, see above ;-)

**Comment by PE5PVB** [comment]
RT in Advanced screen already use the buffering. For RT+ this is not possible.
Also AF and EON do not have a toggle bit, this data is continiously updated.
