### ISSUE TITLE
RT buffering switch

### ISSUE THREAD

**Issue by HyperDX** [PE5PVB/TEF6686_ESP32#204]
Would it be possible to make [RT buffering](https://github.com/PE5PVB/TEF6686_ESP32/commit/1e78088dc015c48f6b84e6334388a2648fa0faa6) switchable in settings?
It would be helpful because RT could be still shown in parts (during fading reception or weak signals). Now I need to wait for full and correct RT line to show it. Which can take very long time if signal is not fair enough.

**Comment by PE5PVB** [comment]
Done.
