### ISSUE TITLE
WiFi icon appears twice due to new battery icon

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#206]
@ohmytime 

Dear Kevin, the battery symbol breaks the layout ...

The WiFi icon appears a second time some pixels left of the current one (and laying over the word kHz), but it's not the same.
And sometimes it's blinking now (either logo or no logo)

[VID_20230806_163927.webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/b76813b8-146b-43df-992e-c328323cfaf0)

![IMG_20230806_163457](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/0be48e83-cc4c-46ad-8116-9370c6b745e3)

Tested with 1dbcd7d50

**Comment by ohmytime** [comment]
When WiFI is on, battery detection is down. Anyway, I will look into this.

**Comment by andimik** [comment]
I was not talking about battery :-)

**Comment by ohmytime** [comment]
> I was not talking about battery :-)

Oh, sorry, you mean the battery icon is too wide , and  occupies the area of wifi icon ?

Last mod to battery layout was made in a rush by @MCelliotG  and still needs some minor adjustments and optimizations. He is on holiday now , and I will have a look to see if I can correct for this.

**Comment by andimik** [comment]
No, the WiFi icon position is wrong for updates. Please check horizontal position.

**Comment by ohmytime** [comment]
<img width="752" alt="图片" src="https://github.com/PE5PVB/TEF6686_ESP32/assets/490477/9622d5bb-780d-4220-a6bc-8ec8e8d3fb55">

Thank you for your remind,  I know this problems now.

**Comment by MCelliotG** [comment]
There were multiple instances of WiFi in the code in different places, looks like I missed one when placing the icon in the new position. It's an easy fix, but I'm on holiday right now.

**Comment by ohmytime** [comment]
> There were multiple instances of WiFi in the code in different places, looks like I missed one when placing the icon in the new position. It's an easy fix, but I'm on holiday right now.

It's okay, I will look into it.

**Comment by ohmytime** [comment]
#220 Fixed.
