### ISSUE TITLE
BAND missing in SW, AUTO not work

### ISSUE THREAD

**Issue by Mike86-CZE** [PE5PVB/TEF6686_ESP32#207]
BANDS switching is now missing in SW.  Instead there is AUTO for LW,MW,SW which does not work.

**Comment by PE5PVB** [comment]
Correct, AUTO does not work yet. Bandswitching is moved to long rotary press

**Comment by andimik** [comment]
@ohmytime 

Kevin, please write such major changings into the commit text. Because you just wrote `Mod: Add auto tunemode for AM band`

**Comment by ohmytime** [comment]
> Kevin, please write such major changings into the commit text. Because you just wrote Mod: Add auto tunemode for AM band

Sorry about that, the readme was too late to update. 
And I will write a clear commit log in the future
