### ISSUE TITLE
Language file broken

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#218]
The https://github.com/PE5PVB/TEF6686_ESP32/blob/main/src/language.h#L2928

And following lines have no closing `, `

**Comment by ohmytime** [comment]
@Elektronik232 Hello, can you fix this error ?

**Comment by ohmytime** [comment]
#219 Fixed.

**Comment by andimik** [comment]
Maybe you could also fix the typos (for example New Zealand and others) which I have marked in the initial commit?

**Comment by ohmytime** [comment]
> Maybe you could also fix the typos (for example New Zealand and others) which I have marked in the initial commit?

It seems that you use a lot of shorthand names, for example:
S. Leone, s. Africa ,and Switzerland. "Luxemb.

I rarely use English, if let me correct those spelling , I have to ask for google.
