### ISSUE TITLE
A small bug in the new battery indicator

### ISSUE THREAD

**Issue by Overland-DX** [PE5PVB/TEF6686_ESP32#223]
![batteri_verdi](https://github.com/PE5PVB/TEF6686_ESP32/assets/102610897/7788d72e-d7bb-42d3-9b04-cdb81005b237)

As you can see, sometimes the values overlap.

**Comment by andimik** [comment]
https://github.com/andimik/TEF6686_ESP32/blob/main/TEF6686_ESP32.ino#L3597

I guess this line causes that.

**Comment by Overland-DX** [comment]
> https://github.com/andimik/TEF6686_ESP32/blob/main/TEF6686_ESP32.ino#L3597
> 
> I guess this line causes that.

At least parts about voltage value. The part that shows the percentage works well as far as I have tested.
When I plug in the usb cable, it jumps up 0.1 volts and shows correctly.

**Comment by ohmytime** [comment]
Thank you for reporting bugs, I just fixed it in PR #225
