### ISSUE TITLE
Ordering of AF List

### ISSUE THREAD

**Issue by mrwish7** [PE5PVB/TEF6686_ESP32#244]
This relates to method A AF, and the example use case relates to BBC stations in the UK. It’s a question on whether it’s possible as an enhancement.

With the advanced RDS screens, the current functionality is that the AF list of a station gets ordered by frequency. However, the frequencies in the AF list (in method A specifically) are actually transmitted in an order defined by the broadcaster. This broadcaster order is shown in RDS Spy, and can be helpful (along with the EON data) for identifying a specific transmitter. BBC transmitters in the UK for example usually have the frequency of the parent transmitter first in their AF list.

It would be very handy to be able to see this original AF list order like in RDS Spy, although I’m aware this is a specific use case and might not be desirable for everyone. Maybe it could be possible for one of the advanced RDS screens to show the sorted order, and the other the original order? I guess it also depends on where the AF list sorting into ascending frequency order happens.

I’d be happy to provide an MPX recording if helpful.

Thanks,
Adam

**Comment by PE5PVB** [comment]
I made an option in the RDS menu to disable auto sorting.
