### ISSUE TITLE
After AF retuning, sometimes the previous frequency remains displayed.

### ISSUE THREAD

**Issue by Mike86-CZE** [PE5PVB/TEF6686_ESP32#246]
If retuning to AF occurs, the previous frequency will sometimes remain displayed on the main screen even though it is no longer tuned.

**Comment by Mike86-CZE** [comment]
https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/ac95dc08-1671-428b-a0f9-afd9bb94640d

**Comment by PE5PVB** [comment]
Can you check again after I applied the changes? I found one thing which could cause this.

**Comment by Mike86-CZE** [comment]
I have not yet been able to reproduce the error in yesterday's release.  So probably OK.
