### ISSUE TITLE
Battery percentage overlaps

### ISSUE THREAD

**Issue by HyperDX** [PE5PVB/TEF6686_ESP32#247]
As in title. When percentage level of battery changes old value is still visible which causes overlaping of the text.

**Comment by PE5PVB** [comment]
Did you have this with the latest beta?

**Comment by HyperDX** [comment]
Yes I tested it with today's [commit](https://github.com/PE5PVB/TEF6686_ESP32/commit/4c8ac2b71624140245cfca6c634d6a5e10f430ae)
Haven't checked if it happens also with voltage.

**Comment by PE5PVB** [comment]
was the old value 99% ?

**Comment by HyperDX** [comment]
No. I post the photo below:
![battery](https://github.com/PE5PVB/TEF6686_ESP32/assets/52051360/56b562fd-183a-4197-a4bd-5b579360dcad)

**Comment by PE5PVB** [comment]
Found and fixed. Please report.

**Comment by HyperDX** [comment]
Yeah fixed. Thanks!
