### ISSUE TITLE
Squelch useless in MPX mode

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#254]
My blue square TEF has a SQL squelch knob. When I turn it, the Mute icon is shown, but audio is normal.

[VID_20230819_110141.webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/e349d0e6-868b-4baa-89a5-e6bbd4227db1)

**Comment by andimik** [comment]
It seems this is due to the fact that I have used MPX as output.

I was assuming only the headphone output will get the MPX, but obviously the internal (mono) speaker plays a combined audio incl. MPX.

**Comment by AaronJowitt** [comment]
In MPX output mode, it's highly desirable that squelch works the same as in L/R mode. Useful to auto mute when feeding an external stereo decoder, or an FM transmitter (low power around the house, or small fm station translator tx).

**Comment by PE5PVB** [comment]
This is not possible because dsp is bypassed.

**Comment by AaronJowitt** [comment]
> This is not possible because dsp is bypassed.

ok, that's a pity.  

thank you Sjef.

**Comment by AaronJowitt** [comment]
> This is not possible because dsp is bypassed.

Just a random thought, no idea if this is feasible.  You can read the signal level and squelch (mute level) setting, and can write the audio output mode (stereo L/R, or MPX), but can't directly mute the MPX output mode.  Assume radio has been user placed into MPX mode, and when the signal drops below squelch threshold, can you just background 'auto switch' the audio mode to normal stereo (which will be in a muted state), and then when the threshold is exceeded, background toggle switch the radio back to MPX mode? A de facto MPX squelch control. To the user, it will appear as if squelch control works normally in both modes.

**Comment by PE5PVB** [comment]
Muting will now also work when MPX mode is selected.

**Comment by AaronJowitt** [comment]
> Muting will now also work when MPX mode is selected.

Nice. thank you!
