### ISSUE TITLE
Slow rotation of squelch knob produces pixel errors 

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#255]
[VID_20230819_113522.webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/99336de0-8c51-4ec1-870a-fce22e0c93b5)

[VID_20230819_113326.webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/a432b2cf-06c8-405e-b062-1223bc7f2a78)

My new blue/dark green square TEF has a squelch knob.

When I rotate it very fast, the display is correct.

When I rotate it slow, there are display errors.

No matter what language is used (in the video it's English resp. German)

**Comment by ohmytime** [comment]
That's a problem, but I don't have the test equipment and Sjef is on vacation.

**Comment by andimik** [comment]
I know of course

**Comment by PE5PVB** [comment]
I tried to reproduce this problem, but failed. Is it still in the latest software?

**Comment by andimik** [comment]
Need to check on one of my TEFs with squelch in the next days.

**Comment by andimik** [comment]
Yes, still the case. Tested with today's commit.

![IMG_20231006_190501](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/b8014e1d-eef6-438b-95d1-f048b7132081)

**Comment by PE5PVB** [comment]
Can you make a movie how to reproduce?

**Comment by andimik** [comment]
There are already two videos in the first posting. I've added a new line, so github shows the videos and not the link.

Maybe slow rotations gives a value out of the range?

**Comment by PE5PVB** [comment]
I changed the way squelch value is shown to a sprite. This should avoid these problems in the future.

**Comment by andimik** [comment]
The highest value should be `OFF` and the lowest `ST`, right?

But now you sometimes (depending on the speed you are turning the know) **cannot** reach these edges, the knob might even stop at `91` (or even lower) resp. `-9` (or even higher) but never reaching `OFF` resp. `ST`.

**Comment by PE5PVB** [comment]
I think you have a harware problem with the potentiometer. Can you please ask others with the same model radio on Discord if they can reproduce this issue?

**Comment by andimik** [comment]
Ah, this was my second idea, that it might be hardware related. As software seems to be OK, let me close it.
