### ISSUE TITLE
ECC wrong for Serbia; Montenegro and Kosovo missing

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#261]
https://www.rundfunkforum.de/viewtopic.php?p=1727011#p1727011

A user from Serbia wrote that ECC is not correct in his case and Kosovo and Montenegro seem to be missing.

[20230819-104405.jpg](https://postimg.cc/fV1Ls0jS)

**Comment by MCelliotG** [comment]
Is he certain that the station transmits the ECC codes correctly?

**Comment by andimik** [comment]
https://www.rundfunkforum.de/viewtopic.php?p=1727117#p1727117

Seems another user has found out the correct codes.

**Comment by PE5PVB** [comment]
Is this already fixed by one of the contributors?

**Comment by MCelliotG** [comment]
I didn't see a commit tbh!

**Comment by PE5PVB** [comment]
Checked it, this was already fixed.
