### ISSUE TITLE
Wrong battery symbol color resp. no values

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#286]
The battery symbol color depends if WiFi was on during start or not.

# issue 1

When WiFi is not connected during start, but activated afterwards, it has a red border color, which might be misunderstanding (low current). So, I propose to have this symbol in grey, too.

# issue 2

There is no value after WiFi is switched off, the battery border color is grey. Workaround: reboot.

## Remark:

It has a (correct) grey border color, when WiFi is connected during start.

**Comment by andimik** [comment]
![IMG_20231006_181708](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/a69bdc0d-cb7f-41e6-9995-29d139c15db7)

**Comment by PE5PVB** [comment]
I've changed something in this matter, but have no possibility to test it. Please check

**Comment by andimik** [comment]
No, there was no improvement, still red border. Tested with latest 8c65f26 dated yesterday. 

This was taken right after configuring WiFi and connecting to the WiFi.
![IMG_20231007_110514](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/b363468c-edac-4de4-93b4-2c075a612336)
After a restart with Wifi on it became grey.

When I switch off Wifi the border is still grey with no value inside.

![IMG_20231007_110845](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/55d117b8-fcdb-4d05-afa6-dfdfdce10e4e)

I need to restart in order to get the value back.

Seems you cannot change the variable during a session?

**Comment by PE5PVB** [comment]
Possibly both are fixed after the WiFi issue in the other issue. Please check.

**Comment by andimik** [comment]
No, not fixed, still showing red border when WiFi is on.

But one issue is fixed: after switching off WiFi, the battery symbol gets its value back.

**Comment by PE5PVB** [comment]
Please check again. If problem is still there, please make a new short movie for reproduction.

**Comment by andimik** [comment]
Yes, fixed.
