### ISSUE TITLE
Scan versus SW Band 

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#287]
The scan function in SW is only working if *AUTO* was selected on **another** band and then switched to SW again. Pressing the *mode* button will change from *MAN* to *BAND*

**Comment by PE5PVB** [comment]
I can't reproduce that problem. Can you make a movie of reproduction?

**Comment by Mike86-CZE** [comment]
It's more of a misunderstanding of the controls than a bug.  In the SW range, if you want to use auto scan, hold down the tuning knob for a long time.

**Comment by PE5PVB** [comment]
So what is your suggestion? Create a menu-item where this can be set?

**Comment by Mike86-CZE** [comment]
Rather just explain the controls to the user (wiki?).  I think many people don't know how to activate AUTO/BAND in SW range.

**Comment by andimik** [comment]
Oh, interesting, yes, it's a good idea.

**Comment by andimik** [comment]
https://github.com/PE5PVB/TEF6686_ESP32/commit/a5181c24632b09bdae1583cde448f25c09305c2c

This commit is similar to the above mentioned issue.
