### ISSUE TITLE
Activated WiFi connection in xdr-gtk produces wrong pixels

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#289]
In advanced RDS view, activating *xdr-gtk* (via WiFi; cable not tested) will immediately lead to wrong pixels on the right (you will see EQ and IMS).

See video, second 6.

[VID_20231002_225708.webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/0530d23d-fb90-4bf8-9acc-11ccbbb3f4ce)

**Comment by andimik** [comment]
Similar in AF/EON view.

**Comment by PE5PVB** [comment]
Found it. Please test.

**Comment by andimik** [comment]
Confirmed, fixed in 1ba582f, so I can close it.
