### ISSUE TITLE
Some fields in AF/EON view not cleared on frequency change

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#290]
In AF/EON view some fields (PI and current received frequency) are not cleared at frequency change (via *xdr-gtk*), and texts have layers of all used pixels.

Expectation: all fields and lines cleared.

See video.

[VID_20231002_230428.webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/0313f90b-03af-4bc3-aeb3-5b475089e75c)

**Comment by PE5PVB** [comment]
You should not be able to tune in the AF/EON screen. I changed the software so it will bring you back to the Advanced RDS view first. Please test.

**Comment by andimik** [comment]
Oh, understood.

**Comment by andimik** [comment]
> I changed the software so it will bring you back to the Advanced RDS view first.

No, not with the up/down icons (see screenshot). You also have to implement it ...

![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/5e8db3d2-8e16-4480-96ad-62ca7fc4e50a)

![DSC_5545](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/607e89eb-17c7-4386-993e-93db2c0ff65f)

**Comment by PE5PVB** [comment]
You are correct. I forgot the seek buttons. I have changed this. Please test

**Comment by andimik** [comment]
Yes, now it works, fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/4b689f23b14ff8cb7b8e611d86c7cc92ac894f84. Therefore, issue closed.
