### ISSUE TITLE
Wifi connection not closed

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#291]
I realized that switching off Wifi in the menu does not work in the past commits. It's still connected although it shouldn't.

The screenshot shows 

> Wi-Fi active: Off

but the Stationlist client IP is still shown, which makes no sense. And I can still connect in *xdr-gtk*.

![IMG_20231006_182304](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/1a0854ad-675a-4d4a-8633-f3fce301403d)

After a reboot Wifi is really off.

**Comment by PE5PVB** [comment]
You are right. I've changed this.

**Comment by andimik** [comment]
**Not** confirmed, **not** fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/e0ac42567568af41faf7f11292221c3a54bf8399

TEF does **not** close the WiFi connection, Stationlist client got a `-` then and the Wifi symbol disappeared (battery symbol still grey). **But you still can connect with `xdr-gtk`.**

**Comment by PE5PVB** [comment]
Should be fixed now. Please test.

**Comment by andimik** [comment]
Yes, fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/9227fe77363e1c24e00129f00912bba64dcb6ed6

Closing the issue.

**Comment by andimik** [comment]
:warning: 
Note: Now the behaviour is different than before. Wifi is **not automatically connected** after configuring. The message `CONNECTED` does **not** appear anymore and in the menu Wi-Fi active is off.

I need to set WiFi active to On in order to connect.

**Comment by PE5PVB** [comment]
You are right. Should be fixed now.

**Comment by andimik** [comment]
Yes, confirmed. Fixed now with https://github.com/PE5PVB/TEF6686_ESP32/commit/94216c9a1536ecbc5dda6ae274375802a08e1f32
