### ISSUE TITLE
ECC field will not be updated

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#292]
During bad reception a station was identified as ECC unknown by mistake, instead of Italy.

![IMG_20231007_120540](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/8791042b-777c-489a-978f-df22e404a551)

But the main problem is, that the field will not be updated until re-tuning to the same frequency. So it's static.

![IMG_20231007_120552](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/1ad2ad91-cd16-4fef-8c79-84604e570c5e)

Please note, that it will be difficult to reproduce it.

**Comment by andimik** [comment]
I now had that again with ECC *unknown* which was never updated to the real value (this time Croatia) before I left the Advanced RDS view. So it can be reproduced.

**Comment by PE5PVB** [comment]
Hmm.. I checked the code but it should be updated every cycle. I can't find the cause of this and haven't been able to reproduce this. Only thing I found is that during scanning it was not updated.

**Comment by andimik** [comment]
That's what I am talking about all the time. If you scan in advanced RDS view, if will not update.

**Comment by PE5PVB** [comment]
I've tested it with an RDS encoder. When in Advanced RDS view, and I change LIC or ECC in the encoder, it automaticly updates on the display, I really don't understand your problem.

**Comment by andimik** [comment]
Which LIC number are you using? Please use 0x00, because for all other values it works.

**Comment by andimik** [comment]
Which ECC number are you using? Please test it again with 0x00 (unknown).

**Comment by PE5PVB** [comment]
ECC is a combination with the first digit of PI code, so I don't understand your question

**Comment by PE5PVB** [comment]
Hmmm... I think I found the cause if this issue. Please test.

**Comment by andimik** [comment]
After a start (as long as hasECC is false) the field is empty (not N/A).

![_20231009_084407](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/d14b72e1-a1ff-440f-9875-6624bb7036d3)

As soon as one station with ECC was received, 

![_20231009_084428](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/09c4e27f-e902-413d-9b63-f144ba0b281c)

all following stations have the correct value.

![_20231009_084445](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/3c489bc4-cf48-4c29-a86c-2f3aafdbdf00)
__

**Comment by PE5PVB** [comment]
Sometimes things take time....

Please check again.

**Comment by andimik** [comment]
ok, seems to be fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/014a4614bbb20b07479b91522308fb56663cfc8c
