### ISSUE TITLE
TP and TA flag

### ISSUE THREAD

**Issue by mtv-alex** [PE5PVB/TEF6686_ESP32#296]
Hello.
If the radio station transmits the TP flag, the receiver will display the TP flag. At the time of transmission of traffic information (transmission of TP/TA flags), the display will also display TP/TA flags.
But the RDS standard allows the transmission of only the TA flag (TP is turned off). By transmitting the TA flag, we inform the receiver that there is a switch to traffic information via EON. If the station transmits the TA flag, then the receiver firmware does not display this (TA flag).
![photo_2023-10-08_21-34-59](https://github.com/PE5PVB/TEF6686_ESP32/assets/147340942/ab538ce2-e078-4b76-8a93-176eb5d4bb57)
![Снимок](https://github.com/PE5PVB/TEF6686_ESP32/assets/147340942/27aa6a8d-ac3e-4439-a865-6b5efbd8cb2d)

**Comment by PE5PVB** [comment]
I've changed the TA flag behaviour.

**Comment by mtv-alex** [comment]
After installing the new firmware it worked. Thank you.

**Comment by andimik** [comment]
Yes, I also tried it and it worked.

**Comment by andimik** [comment]
Well, it shows `TA` for EON only stations, this could be misunderstanding, although it's correct. But we have the `EON` for this reason.
