### ISSUE TITLE
Flickering of SW meter value during scan

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#297]
During an `AUTO` scan, the Shortwave (SW) meter value (see video, like `31 m` is flickering. All other display fields are not affected. Seems the meter band value is calculated from the frequency.

[VID_20231010_201109.webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/408cda48-abda-4a18-ac47-4d9b89ded129)

No matter which SW band and no matter if tuning up or down.

**Comment by PE5PVB** [comment]
Fixed.

**Comment by andimik** [comment]
yes, fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/b7f187058c3416d9a6fe3da15476b1ef419855c5

Closing the issue.
