### ISSUE TITLE
RT+-indicator

### ISSUE THREAD

**Issue by lxsxl** [PE5PVB/TEF6686_ESP32#299]
RT+-indicator disappears in the following sequence of steps:

1, switch to advanced RDS-screen, station where RT+-indicator is active
2. switch to EON/AF-screen
3. switch back to advanced RDS-screen, then the RT+-indicator stays inactive, although RT+ is still running

**Comment by PE5PVB** [comment]
Fixed.

**Comment by andimik** [comment]
confirmed, fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/08deb58ae4277ce99a8ad406eb3c340c2721f412

Can be closed.

**Comment by lxsxl** [comment]
Yeah, it's okay now!
