### ISSUE TITLE
Unreadable character ' (apostrophe)

### ISSUE THREAD

**Issue by mtv-alex** [PE5PVB/TEF6686_ESP32#302]
Hello.
I noticed that if the name contains the symbol ( ' - apostrophe), the receiver cannot display it.
![photo_2023-10-12_20-47-22](https://github.com/PE5PVB/TEF6686_ESP32/assets/147340942/efe38916-8bb8-4e5d-b448-0fd0d15dfec5)
![Снимок](https://github.com/PE5PVB/TEF6686_ESP32/assets/147340942/663ebae8-8c93-43d3-907a-2f69bcdeff0d)

**Comment by PE5PVB** [comment]
Can you get me a MPX recording of that station?

**Comment by mtv-alex** [comment]
https://disk.yandex.ru/d/XWXaOIn7XbzXAg
This is an edited file from which you can extract the MPX (via SDR Console). F=87.90 MHz.

**Comment by PE5PVB** [comment]
There is no MPX in that file. But I think I found it. Seems that ` was not in use in the original RDS tables. Please check.

**Comment by PE5PVB** [comment]
I checked again the latest RDS table from the EBU, ` is not assigned. It's very weird this broadcaster uses it.

**Comment by mtv-alex** [comment]
Yes, this is a very interesting symbol. The sign is number 96. According to the table, this means... two vertical lines. Those. According to logic, everything showed correctly.
I can assume that a different version of the symbol table is being used. We have several of them: G0, G1 and G2.
![Снимок_2](https://github.com/PE5PVB/TEF6686_ESP32/assets/147340942/a914f68c-cc5c-48c3-833a-0dbf4d94c752)
![Снимок_3](https://github.com/PE5PVB/TEF6686_ESP32/assets/147340942/e2eee968-db56-488f-82d2-fc03d8ef3153)

**Comment by mtv-alex** [comment]
But in this table it is present under the same number: 0х60
![Снимок_4](https://github.com/PE5PVB/TEF6686_ESP32/assets/147340942/7ec49258-91bb-4d7b-b770-eb432c77e35e)

**Comment by PE5PVB** [comment]
Can you get me the different RDS characterset tables G0, G1 and G2 (not as picture). And also some explaination how to detect it?

**Comment by mtv-alex** [comment]
I only found such old tables: https://pira.cz/rds/rdschars.pdf
I don't have any new ones. There is such a symbol table. But it is for 2009 and changes could have been made during this time.
As I understand it, an ASCII character table is used for the display. Looking at the updated table, I see that the symbol ` is hidden under the number 96 (DEC). https://www.ascii-code.com/
And apparently changes were made to this table, which were later transferred to the RDS standard.
For a detailed analysis, it is better to use RDS Spy. You can see everything in it, which characters are passed to DEC, HEX.

**Comment by PE5PVB** [comment]
Well. Currently I already have remapped 0x60 to `
If anyone can provide the complete ASCII lists for G0, G1 and G2 and give a explanation how to detect G0, G1 or G2 please let me know.

Please test the character and report back.

**Comment by lxsxl** [comment]
The character-sets should be completely in the RDS specification (pdf-pages 118 - 138).

**Comment by PE5PVB** [comment]
Can you please post the document you refer to? There are several different versions. I currently use ISO62106. I can't find any reference to the `-char.

**Comment by lxsxl** [comment]
That's the document I meant. 0x60 is 0x2016 DOUBLE VERTICAL LINE (and not apostrophe, see pdf-page 121). I didn't find this kind of apostrophe in the tables, even not in the cyrillic part. But I didnt't read this whole thread, so I would agree with you that the broadcaster is using an old table (and DEVA is still using it too...). Standard-non-conformity is always a problem ...

**Comment by PE5PVB** [comment]
Well, since no-one will use the double vertical bar, I will replace it with a `. Still waiting for confirmation of @mtv-alex if this solved his issue.

**Comment by mtv-alex** [comment]
Yes, the problem is solved.
![photo_2023-10-14_09-18-52](https://github.com/PE5PVB/TEF6686_ESP32/assets/147340942/19c5f359-ec01-4a23-a072-1a11a3481a69)
