### ISSUE TITLE
Language code table

### ISSUE THREAD

**Issue by mtv-alex** [PE5PVB/TEF6686_ESP32#303]
Hello.
Is the entire language code table used? In the RDS 1A group we can transmit the name of the country and the broadcast language. The radio station's broadcast language is set to 79 (HEX) = Belorussian. But the receiver does not recognize him - writes "unknown"
![photo_2023-10-12_20-47-22 (2)](https://github.com/PE5PVB/TEF6686_ESP32/assets/147340942/a21e9167-0a55-406d-90ec-65379b3c3a9a)
![Снимок_2](https://github.com/PE5PVB/TEF6686_ESP32/assets/147340942/a4acd0d6-a7c3-4932-a9bc-52ca40e18017)

**Comment by PE5PVB** [comment]
You can check the current LIC table in the bottom of the language.h file.
Please add the missing languages to it, or post the list here.

**Comment by mtv-alex** [comment]
Yes, if you can, please add Belarusian language for the item LIC. According to the RDS table, it has the number: HEX = 79, DEC = 121.
Other major languages are present. Thank you

**Comment by PE5PVB** [comment]
Do you have a full list of LIC languages with their address?

**Comment by PE5PVB** [comment]
I already found a table and applied it. Please test.

**Comment by mtv-alex** [comment]
Yes, I see that the language has been added in the "language.h" file. Thank's

**Comment by mtv-alex** [comment]
Somewhere there are not enough languages, or a space. Or vice versa - overkill.
Where there is a Belarusian language, Armenian is shown; where Russian is Persian. The difference is 4 lines.

**Comment by andimik** [comment]
Maybe it helps to add the numbers as comments again to the languages?

**Comment by mtv-alex** [comment]
A comparative analysis of language codes according to the RDS standard was carried out with those codes that were introduced (language.h). All this is summarized in a table. Everything that is green matches the RDS standard, everything that is red does not. As I said, there are a few blank lines missing.
[LIC.xlsx](https://github.com/PE5PVB/TEF6686_ESP32/files/12906727/LIC.xlsx)

**Comment by PE5PVB** [comment]
Thanks @mtv-alex . I just modified the table.

**Comment by andimik** [comment]
And thanks for following my suggestion :-)

**Comment by PE5PVB** [comment]
Thank ChatGPT for that

**Comment by mtv-alex** [comment]
Everything is fixed Thank you!
![photo_2023-10-15_09-48-14](https://github.com/PE5PVB/TEF6686_ESP32/assets/147340942/def40a82-70e6-41d7-a299-2db50b36d35e)
