### ISSUE TITLE
Auto-search for radio stations with auto-saving them into memory cells

### ISSUE THREAD

**Issue by Yurij20** [PE5PVB/TEF6686_ESP32#306]
Is it possible to add the ability to auto-search with auto-saving radio stations to memory cells?  As an implementation option, we turn on the desired range, go to the main settings menu, there we launch the Autosave stations item and the receiver scans the entire current range and writes radio stations to memory cells

**Comment by andimik** [comment]
All different stations or all found frequencies?

What about SW? It won't stop in a band and will continuously scan all SW bands.

**Comment by PE5PVB** [comment]
This is not an issue but a feature request. Please post this in section "Discussions"
