### ISSUE TITLE
Hidden text 1/2 in Advanced RDS view 

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#315]
The right margin for the new application detection is too far right as the page numbering (`1/2`) is partially hidden.

And we could add the text `Press MODE TO TOGGLE PAGE`...

[VID_20231015_095645.webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/d5f199be-820a-4a35-a2e0-9b67159cd86f)

**Comment by PE5PVB** [comment]
Fixed
