### ISSUE TITLE
Different frequencies of the OIRT range are not saved

### ISSUE THREAD

**Issue by Yurij20** [PE5PVB/TEF6686_ESP32#316]
Different frequencies of the OIRT range are not saved
https://youtu.be/ozmtukSKh3k?si=b9HkwH9AfootlQ9z

**Comment by andimik** [comment]
Have you done a complete reset first?

Seems not, as there is a MEM position 87.00 MHz, which is outside of the FM band.

![image](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/1944ffdc-325d-45bb-86c3-1a1536705459)

**Can you repeat that on MEM positions <30?**

The headline is wrong. All of the frequencies in your video are saved, but it seems they are overwritten

As you did not write down what we see in your video and what is wrong, let me summarize:

You are saving 66.44 MHz on MEM 52
then 72.92 MHz on MEM 53 but get it on 52 as well
then 73.16 MHz on MEM 54 but get it on 52 and 53 as well

**Comment by PE5PVB** [comment]
Thanks. Fixed the problem.

**Comment by Yurij20** [comment]
I checked.  On the OIRT band everything is saved normally, but on the LW, MW, SW bands there are still problems: it remembers the frequencies themselves but displays them incorrectly.  In the video below, I remember 2 frequencies of each range and switch them back and forth.  Here everything is clearly visible:
https://youtu.be/dIp1Nvrmwk4?si=yww2uckqx5iST9UP

**Comment by PE5PVB** [comment]
Fixed that one.

**Comment by Yurij20** [comment]
Thank you) everything is fixed.  The interference from the display on the receiver has also disappeared.  So please compile new firmware releases in the format that was compiled today)
