### ISSUE TITLE
Problems with the function: Touch rotating

### ISSUE THREAD

**Issue by Overland-DX** [PE5PVB/TEF6686_ESP32#321]
I have noticed that the "Touch rotating" function no longer works. 

I don't really know what this function actually is, but I used it often in the AM band. When I set Touch rotating ON, I could tune with the tuning knob even if the display was OFF. 
It was very useful for finding weak stations as noise from the display could wipe these stations out completely.

**Comment by andimik** [comment]
Me too. I have never understood that menu option. Therefore, I could not translate into German.

**Comment by ohmytime** [comment]
It means :
You can still change frequency after screensaver is triggered

I just add this function back #323

**Comment by andimik** [comment]
So let's use another menu text for that.

**Comment by ohmytime** [comment]
> So let's use another menu text for that.

OK， you can translate to your local language , to make it easier to understand.

**Comment by Overland-DX** [comment]
Thanks so much :) It works fine now. I have the gray china model and it produces so much noise from the display that it is no use searching for stations on the LW and MW band with the display on. Even on the SW band, the weak stations disappear with the display switched on.
Andimic:
I have translated it roughly like this: Allow to tune with display off.

**Comment by andimik** [comment]
No I mean that even the English text is not well understandable.
