### ISSUE TITLE
Set a ban on PS rotation when RDS reception is weak

### ISSUE THREAD

**Issue by Yurij20** [PE5PVB/TEF6686_ESP32#327]
I apologize for bringing up this topic again.  I compared the work with old firmware and came to the conclusion that in PS the line rotates even with weakened RDS reception and often collects errors.  With strong RDS reception there are no problems.  In older firmware, under the same reception conditions, with a weakened RDS signal, the PS line does not rotate at all and resumes rotation when strong RDS reception is achieved.  There is one last suggestion, if possible, to set a ban on dynamic PS rotation when RDS reception is weakened, thereby making the PS line rotate only with strong 100% RDS reception.  This will minimize the occurrence of errors when rotating the PS.  If this is not possible, then I will not raise this issue anymore.  Thank you.

**Comment by PE5PVB** [comment]
Currently there is already a compare between two different PS cycles. If both results are not the same it won't be refreshed. So there is no way to detect if the cycle you received and want to freeze is a correct one. And maybe it only contains the word "FM".
