### ISSUE TITLE
Sudden reboot during RDSSPY WiFi connection 

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#33]
During an RDSSPY connection via WiFi the TEF rebooted suddenly.

After this reboot RDSSPY received no data at all. I have switched it off an on several times to get it working again.

This sudden reboot happened a second time some minutes later.

I have no idea what went wrong here.

Using e2cc859, old Win 7 laptop 32 bit. WiFi is my hotspot on the mobile next to the TEF.

**Comment by PE5PVB** [comment]
Is it possible your WiFi signal is a bit low?

**Comment by andimik** [comment]
You mean a low signal caused the reboot?

**Comment by PE5PVB** [comment]
It can be possible. I still have to build in a check, when wifi is lost, servers should stop.

**Comment by andimik** [comment]
Yes, but I expected resuming after having WiFi again. This seems not to be the case.

**Comment by PE5PVB** [comment]
Not possible, the socket is closed then.

**Comment by andimik** [comment]
Understood. But what do you recommend next?

I have tried

- switching WiFi off and on
- restarting tuner
- setting mode to xdr-gtk and back to rdsspy

I can't tell you what has helped (, luckily) at the end, but the TEF should at least tell the user that the connection has been lost and propose the next step.

And we shall not have a reboot here.

**Comment by PE5PVB** [comment]
Yes I know. But has not been implemented yet. This is still a development version.
Today I rewrote the whole RDS part.

**Comment by andimik** [comment]
Ok, will test it in the next days.

**Comment by PE5PVB** [comment]
I modified the software to switch off the brownout reset from the ESP32. This was sometimes triggered due design flaws in the Chinese receivers.
