### ISSUE TITLE
Error in the interface when switching saved radio stations

### ISSUE THREAD

**Issue by Yurij20** [PE5PVB/TEF6686_ESP32#330]
When switching saved radio stations, sometimes the interface in this part of the display fails.  Circled in the photo below

https://disk.yandex.ru/i/rzkZg6yP5PjWPQ

**Comment by Yurij20** [comment]
![Uploading 20231020_091912.jpg…]()

**Comment by andimik** [comment]
![20231020_091912](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/44df6682-fc3d-4993-bedc-5d241c4143c8)

BTW

You can attach pictures (and short videos and files) also here in github.com. In some browsers you need to switch to desktop view in order to do that...

**Comment by PE5PVB** [comment]
Can you get me a way to reproduce this? What frequencies at what preset and how to reproduce?

**Comment by Yurij20** [comment]
This problem appeared periodically, so there is no way to reproduce it.  I installed the latest firmware release and it doesn't seem to show up anymore

**Comment by PE5PVB** [comment]
Well. Possibly fixed on the way. if it occurs again, please reopen with reproduction plan.
