### ISSUE TITLE
Blue RDS fields also shown in menu

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#333]
As soon as reception got worse and the RDS fields (PI, PS, PTY) turned blue instead of yellow, these texts are shown in the menu (all pages, in all languages) afterwards.

![IMG_20231020_140215](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/26a5a4d1-05e2-4e33-a385-80c758456ccb)

Hint: Radiotext is not affected.

**Comment by PE5PVB** [comment]
Fixed

**Comment by andimik** [comment]
Yes, confirmed.
