### ISSUE TITLE
AF-indicator in case of no AF

### ISSUE THREAD

**Issue by lxsxl** [PE5PVB/TEF6686_ESP32#336]
If there isn't any AF transmitted, the "-B"-indicator is switched to active:

![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/140750201/ee1fdefe-efcf-4a24-860a-c5efaff8bb4f)

**Comment by andimik** [comment]
Funny bug :-)

**Comment by lxsxl** [comment]
Something is strange, I also received a station without AF but also without the "-B"-indicator:

![IMG_8350](https://github.com/PE5PVB/TEF6686_ESP32/assets/140750201/2bd7e4db-682a-4edd-8846-41e75ac86028)

**Comment by PE5PVB** [comment]
Fixed.

**Comment by lxsxl** [comment]
It works good, issue can be closed.
