### ISSUE TITLE
EON overload

### ISSUE THREAD

**Issue by lxsxl** [PE5PVB/TEF6686_ESP32#341]
Too many EON-networks cause overload on the first EON/AF-screen:

![IMG_8349](https://github.com/PE5PVB/TEF6686_ESP32/assets/140750201/b7581e92-44cb-4638-9e85-dda578974d7d)

**Comment by PE5PVB** [comment]
Fixed

**Comment by lxsxl** [comment]
It works fine now, you can close this issue.
