### ISSUE TITLE
Problems with the new SPI speed function.

### ISSUE THREAD

**Issue by Overland-DX** [PE5PVB/TEF6686_ESP32#348]
It looks like the new feature isn't working as it should. It detects the value set in User_Setup.h, but does not register desired values set in the menu.
Like for example when I set the value to 4MHz in user_setup.h, I get a noticeably slow radio. If I then set it to 60MHz in the menu, there is no difference. If I turn the radio off and on, it always goes back to the value set in user_setup.h.

**Comment by ohmytime** [comment]
Restore defaults after shutting down, that's what I originally planned(Memory can be added if needed)
As for the SPI change not taking effect, I will investigate again.

**Comment by PE5PVB** [comment]
Should be fixed. Please use the tft_espi library from ohmytime. https://github.com/ohmytime/TFT_eSPI_DynamicSpeed

**Comment by andimik** [comment]
and don't forget to modify the TFT_eSPI configuration **again** like described in https://github.com/PE5PVB/TEF6686_ESP32/wiki/Installing-the-software

**Comment by PE5PVB** [comment]
Is it all ok now? Then please close.
