### ISSUE TITLE
AF method B detection

### ISSUE THREAD

**Issue by lxsxl** [PE5PVB/TEF6686_ESP32#350]
I think that method B detection needs a bit adjustment. I received the following data:
![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/140750201/00d6c739-7bda-4d6c-983c-4c796ef4f1b5)

Translated to AFs it is as follows:
#14 / 102,7
89,1 / 91,0
102,7 / 91,5
92,8 / 94,2
94,5 / 95,5
98,7 / 102,8
104,4 / 104,5
107,2 / filler

102,7 is < 50 % within this list and there is only one single list, so it should be detected as method A.

**Comment by lxsxl** [comment]
And same for this:
![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/140750201/c342d6d8-a633-482d-9e4e-4c2429f46f56)

This is:
#3 / 106,1
98,9 / 105,3

is also be method A (but detected as method B)

**Comment by PE5PVB** [comment]
Is it correct that your radio is tuned to 102.7 in example 1 and to 106.1 in example 2?

**Comment by lxsxl** [comment]
Yes, that's correct, sorry that I didn't mention it.

**Comment by andimik** [comment]
There is another bug. I have (at least) a station with Method A, but it's detected as Method B.

```
nc 127.0.0.1 7376 | redsea -hE | grep freq
{"pi":"0x5210","group":"0A","alt_frequencies_a":[91000,101000,104700,105000,105000,105200,105500,107300],"bler":6,"di":{"compressed":true},"is_music":false,"prog_type":"News","ta":false,"tp":true}
{"pi":"0x5210","group":"0A","alt_frequencies_a":[91000,91000,105000,105000,105200,105500,107300,107300],"bler":10,"di":{"compressed":true},"is_music":false,"prog_type":"News","ta":false,"tp":true}
{"pi":"0x5210","group":"0A","alt_frequencies_a":[91000,91000,105000,105000,105200,105500,107300,107300],"bler":6,"di":{"compressed":true},"is_music":false,"prog_type":"News","ta":false,"tp":true}
{"pi":"0x5210","group":"0A","alt_frequencies_a":[101000,104700,105000,105000,105000,105200,105500,105500],"bler":8,"di":{"stereo":false},"is_music":false,"prog_type":"News","ta":false,"tp":true}
{"pi":"0x5210","group":"0A","alt_frequencies_a":[101000,104700,105000,105000,105000,105200,105500,105500],"bler":6,"di":{"compressed":true},"is_music":false,"prog_type":"News","ta":false,"tp":true}
{"pi":"0x5210","group":"0A","ps":"RADICALE","alt_frequencies_a":[91000,101000,104700,105000,105000,105200,105500,107300],"bler":2,"di":{"stereo":false},"is_music":false,"prog_type":"News","ta":false,"tp":true}
```

**Comment by PE5PVB** [comment]
I've added an extra Method B probe. Please test if this is successfull.

**Comment by lxsxl** [comment]
Everything I tested (including the examples above) was detected in the right way. Even method B with this crazy configuration (only number 1 and one frequency) is fine.

**Comment by PE5PVB** [comment]
So this one can be closed?

**Comment by lxsxl** [comment]
I would say YES
