### ISSUE TITLE
RDS Block A, B and C wrong error calculation

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#354]
The error calculation for RDS blocks A, B and C is broken, it's similar to https://github.com/PE5PVB/TEF6686_ESP32/issues/189

I could repeat that several times.

![IMG_20231024_120257](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/fee2e18e-5db9-4745-984a-787f040b18b5)
![IMG_20231024_115937](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/089ead88-8737-4dae-9855-80183a744dda)

For the hidden pixels on the left bottom corner I'll open a separate issue.

**Comment by PE5PVB** [comment]
This this only on block A?

**Comment by PE5PVB** [comment]
I modified the software so the "leds" are always written. For some reason they are sometimes not updated correct, while software says so. I guess a glitch in the compiler.

**Comment by PE5PVB** [comment]
@andimik Please confirm if the problem is fixed.

**Comment by andimik** [comment]
will test it in the next days.

**Comment by lxsxl** [comment]
For me it is a bit strange that block A has almost no errors when the other blocks are shown with multiple errors. Or is there a technical reason that block A is less affected by errors?

**Comment by PE5PVB** [comment]
Possibly because Block A is always the same.

**Comment by lxsxl** [comment]
Of course, block A should remain the same. I thought that the LEDs display the error in that single block? So even if PI-code remains the same but a single block A was not completely received it should be a red LED, or am I wrong?

**Comment by PE5PVB** [comment]
Don't know. Error data comes directly from the TEF chip. Possibly there is a kind of algorithm inside.

**Comment by andimik** [comment]
For me it is solved, although sometimes group "LED" B, C, D are blinking very rapidly. But Rdsspy says BER = 0.
