### ISSUE TITLE
Pixels on left bottom corner in advanced RDS view after scanning there

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#355]
When you scan in Advanced RDS view there are pixel errors on the left bottom corner. Seems there is a number written but it's hard to find out.

Only reboot helps to let them disappear.

![DSC_5576](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/19c5d80f-fdd1-4307-b643-a0baad7fd36e)

[VID_20231024_122303.webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/41b1f893-6054-4e21-9fba-7bea48d97bd8)

**Comment by MCelliotG** [comment]
Maybe some LIC value? Perhaps these infos should be set to no wrap.

**Comment by PE5PVB** [comment]
Fixed.

**Comment by PE5PVB** [comment]
@andimik Please confirm if the problem is fixed.

**Comment by andimik** [comment]
Confirmed. Could not see them in yesterday's beta release.
