### ISSUE TITLE
FM double de-emphasis?

### ISSUE THREAD

**Issue by AaronJowitt** [PE5PVB/TEF6686_ESP32#357]
build 181023. 

FM settings  > FM deemphasis: 50us
RDS settings > Region: Europe

Is FM audio de-emphasis being applied by both settings, resulting in unintended double de-emphasis?   On a quick listen, sounds better/normal with FM de-emphasis set to None.

**Comment by PE5PVB** [comment]
Double de-emphasis is not possible.
I already removed the de-emphasis setting on RDS region last night.

**Comment by AaronJowitt** [comment]
Thanks - makes sense the TEF wouldn't support that. I probably haven't listened long enough and suspected the wrong thing. So is;

FM settings > FM deemphasis: off

wrong?  After being changed to 'off', it sounds like there is some de-emphasis (maybe 50us?) still being applied.

**Comment by AaronJowitt** [comment]
> Thanks - makes sense the TEF wouldn't support that. I probably haven't listened long enough and suspected the wrong thing. So is;
> 
> FM settings > FM deemphasis: none
> 
> wrong? When changed to 'none' it sounds like there is some de-emphasis (maybe 50us?) still being applied.

**Comment by PE5PVB** [comment]
You are right, there was a bug in the de-emphasis. I've fixed that. Please check and report.

**Comment by AaronJowitt** [comment]
Confirmed fixed in today's beta.  Thank you!
