### ISSUE TITLE
AF-lists without green and red colours

### ISSUE THREAD

**Issue by lxsxl** [PE5PVB/TEF6686_ESP32#359]
I noticed that the AF-lists are now (alost?) always without green and red coloured frequencies. When you start the EON/AF-screen the list is fine at the first moment (WITH some frequencies in green and/or red). But after a part of a second the list is cleared and re-built and is then without colours. This happens in method A as well as in method B and also with the autosort-setting on or off.

**Comment by PE5PVB** [comment]
Did you test this with the latest build? Because there was a problem in the earlier build which could cause this.

**Comment by lxsxl** [comment]
I just compiled the latest code and it is fine again. You can close this issue.
