### ISSUE TITLE
Stereo indicator does not work correctly when switching saved stations

### ISSUE THREAD

**Issue by Yurij20** [PE5PVB/TEF6686_ESP32#364]
When you switch stored stations to a location with a monaural station or to a frequency with no signal, the stereo indicator does not go out completely

https://youtu.be/-UcPqG_tuY4?si=nCmEOm9VGNHoE0Zw

**Comment by PE5PVB** [comment]
Fixed.

**Comment by PE5PVB** [comment]
@Yurij20 Please confirm and close.

**Comment by Yurij20** [comment]
I checked, everything is fixed and works fine)
