### ISSUE TITLE
CT has glitches 

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#368]
Described initially by radiofan98 at https://discord.com/channels/1053804249651359765/1080501413651693578 , I also had this problem with beta from 28th Oct.

![IMG_3726](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/463c0e91-8326-421b-b038-faf877d85e6e)

![_20231030_003011](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/af7c9ee9-8f48-40cb-a5b0-c8f26873708b)

**Comment by PE5PVB** [comment]
Do you have a step-by-step reproduction method? I can't figure it out.

**Comment by andimik** [comment]
I will try to reproduce it, but you might need at least one station where CT is wrong or/and signal is disturbed.

**Comment by PE5PVB** [comment]
Hopefully fixed.

**Comment by lxsxl** [comment]
If a frequency gets weaker and RDS is lost, the time will switch to secondary colour but the font "shivers". And as long as RDS-reception won't return, CT stops running (shows permanently the last received CT-signal). If you switch to a different frequency and duration of RDS-loss is longer than one minute you will observe an overlyay.

**Comment by PE5PVB** [comment]
OK. I'll check again. And yes, it's correct that the clock is frozen on RDS loss. It's ment to be.

**Comment by PE5PVB** [comment]
Fixed. Please check.

**Comment by andimik** [comment]
I just could read `1:61` due to reception error. I guess you should check if the time is plausible (same for PIN, where I also have seen >24:00)

**Comment by PE5PVB** [comment]
I added extra checks

**Comment by lxsxl** [comment]
Glitches seem to be gone. But what I don't understand: Why is the time stopped in case of poor reception but in case of tuning to a different station it will step up to the right time (even if there was no signal on the newly tuned frequency)? Imho it would be good to always fall back on the RTC. Thoughts of a layman, if this is too difficult to implement it can remain like it is.

**Comment by PE5PVB** [comment]
Well I choose for this, because in my opinion when CT is detected on a service, it should show the values. When signal is lost, clock is not updated, so it stays that way. Maybe I'm a nerd on this ;-)

**Comment by lxsxl** [comment]
Okay, I agree. What about this idea: If RDS is lost, keep the time running in secondary colour. If RDS returns (without tuning) also keep it running in secondary colour until the next CT-code is received. So it would be identical to the situation when you tune to a different frequency.

**Comment by PE5PVB** [comment]
Yes, can do. Sorry for being a nerd ;-)

**Comment by lxsxl** [comment]
You‘re perfect as you are 👍 on need to apologize

**Comment by PE5PVB** [comment]
Done

**Comment by lxsxl** [comment]
CT was received at 20:18, then I disconnected the antenna (remained on that frequency). Time switched as follows (of course in secondary colour): 20:19 - 20:20 - 20:19 - 20:20 - 20:21. Then I reconnected the antenna and on receiving RDS again the time went back to 20:18 (in primary colour).

**Comment by PE5PVB** [comment]
Fixed.

**Comment by lxsxl** [comment]
As far as I tested the time works well in all variants. For me this issue may be closed.
