### ISSUE TITLE
AF page 2 has no frequencies and pixel errors

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#369]
When AF list is too long, the page 2 has an error in latest beta from 28th and no frequencies are displayed on page 2. 

Switching back to page 1 will not show them as well. Only restart helps.

![IMG_20231030_003536](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/170fab78-5bf9-4b72-8327-b4d45f3bbcd0)

**Comment by andimik** [comment]
I fear it has to do with (too late) Method B detection.

**Comment by PE5PVB** [comment]
Fixed.

**Comment by PE5PVB** [comment]
@andimik Please confirm and close.

**Comment by andimik** [comment]
Fixed.
