### ISSUE TITLE
Small bug - FrequencyColor parameter do nothing

### ISSUE THREAD

**Issue by zygmund2000** [PE5PVB/TEF6686_ESP32#372]
Hi,

I'm trying to create a new color theme and I came across a definition that doesn't work in gui.cpp:
eg. `      FrequencyColor = 0x03DA;` doesn't work in any theme, color is the same as primary color.

**Comment by PE5PVB** [comment]
You are right. It's a resedue from the past. I removed it. If you find any more unused color references, please let me know.

**Comment by zygmund2000** [comment]
It was nice to change this color, why can't it be like before?

**Comment by PE5PVB** [comment]
Why should you? Too much different colors can make you crazy like a clown ;-)

**Comment by PE5PVB** [comment]
bde1331

**Comment by zygmund2000** [comment]
So why not? I don't need colors like clown or LGBT, but colors always are nice ;)

**Comment by zygmund2000** [comment]
I've changed 1 line:
`          FrequencySprite.setTextColor(FrequencyColor, PrimaryColorSmooth, false);`
And now it seems to look as before.
