### ISSUE TITLE
myLanguage[language][56] shown too short

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#378]
The message `myLanguage[language][56]` (in English `FAILED`) is shown just for a very short time (<1 sec.)

**Comment by PE5PVB** [comment]
Where is it shown too short?

**Comment by andimik** [comment]
When you have WiFi disabled and turn it on (but WiFi not found), then the message is too short to read.

**Comment by PE5PVB** [comment]
Fixed.

**Comment by andimik** [comment]
having checked the source code and guess this is fixed.
