### ISSUE TITLE
AF/EON show red color instead of green at 2nd or 3rd scan

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#381]
When you are in advanced RDS view and go the first time to AF/EON view the colors are correct.

But if you repeat that **without** changing the frequency green frequencies might become red.

**Comment by PE5PVB** [comment]
When you repeat this over and over again will they sometimes end up green?
Is this station possibly somewhat weak?

**Comment by andimik** [comment]
No, I expect to have it written in green on all my attempts, as this is my local transmitter (>60 dBuV).

Have repeated it with other stations as well, same result.

If it would be too week, the color will be yellow, but not red.

**Comment by PE5PVB** [comment]
OK, does it always stay red or sometimes green after several attempts?

**Comment by andimik** [comment]
Good question, I just repeated it around three times for each frequency. I will try more attempts.

**Comment by PE5PVB** [comment]
Should be fixed.

**Comment by lxsxl** [comment]
In my last tests it seemed to work fine.

**Comment by andimik** [comment]
Yes, looks good, have not seen that again. Therefore closing.
