### ISSUE TITLE
RDS logo reacts very slow

### ISSUE THREAD

**Issue by lxsxl** [PE5PVB/TEF6686_ESP32#386]
Idk if you are still working on this but actually the RDS logo reacts very slow: RDS data are already received when RDS logo is still inactive and also vice versa, when RDS get's lost the logo will remain until there is almost nothing to be heard anymore.

**Comment by PE5PVB** [comment]
I can't reproduce that

**Comment by lxsxl** [comment]
https://github.com/PE5PVB/TEF6686_ESP32/assets/140750201/5984db97-ce49-4edf-a410-d583f9c1f002

**Comment by lxsxl** [comment]
https://github.com/PE5PVB/TEF6686_ESP32/assets/140750201/c8ddf30e-d493-450f-9a7b-70890e508dc4

**Comment by lxsxl** [comment]
![IMG_8506](https://github.com/PE5PVB/TEF6686_ESP32/assets/140750201/fed60a99-5bfe-4ba2-9236-d03490cdd501)


those are the RDS settings. In the first video you can see disconnecting the antenna what causes loss of reception but RDS remains active and everything is in primary colour. The second video is vice versa (reconnecting antenna and you can see that RT is updated though RDS indicator is off. (Not recorded in the videos: If I tune up and down to the same frequency RDS will be immediately active).

Hope I found the reason: If I turn off „RDS-Filter“ it works fine, so likely there will be a bug.

**Comment by PE5PVB** [comment]
Fixed.

**Comment by lxsxl** [comment]
I confirm that it works fine. Close this issue as completed.
