### ISSUE TITLE
Support for 2nd EON frequency in case of multiple tuning frequency

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#387]
I've realized that the EON Frequency might not be correct as the tuned frequency is used more than once.

![IMG_20231103_203153](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/c46362bd-ffd5-4668-8e52-bc92950d132f)

In my example I have tuned to 94.7 (RADIO-K is described as OE2 K in the below screenshots) which is used twice here. So the EON frequency for OE 1 can be either 87.7 or 89.7. 

I've checked the official frequency table

![image](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/33411454-d6e6-44f9-880b-db7ce3e2c193)

![image](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/e7415a62-2c88-43a1-9977-9583a72a299a)

In RDS, both are mentioned:

```
{"pi":"0xA502","group":"14A","other_network":{"pi":"0xA201","kilohertz":89700,"tp":false},"prog_type":"No PTY","tp":true}
{"pi":"0xA502","group":"14A","other_network":{"pi":"0xA201","kilohertz":87700,"tp":false},"prog_type":"No PTY","tp":true}
```

So I propose that both possible frequencies are shown alternating as this is not unique.

**Comment by PE5PVB** [comment]
So what is your suggestion?

**Comment by andimik** [comment]
Write a second line with the frequency and in front the word `or`

```
A201   OE 1       87.7
           or     89.7
```

**Comment by lxsxl** [comment]
Did you consider that we already added (at total) three EON-frequencies on advanced RDS-screen to resolve this problem?
Anyway if more than one EON-frequency shall be shown also on EON/AF-screen it would be a further reason to separate AF and EON screens.

**Comment by andimik** [comment]
Oh, I didn't know that. I was never using the Advanced RDS view for AF and EON.

**Comment by PE5PVB** [comment]
Can you open a topic in Discussions about this? This is a feature request.
