### ISSUE TITLE
Disappearing content during scan

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#388]
I don't know if this ever has been discussed, but during a scan some content is disappearing for a while, probably due to too low audio level (see `M`-bar).

[VID_20231103_205221.webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/4961089f-39a2-487e-99b4-6a7403819446)

In my example I have scanned OIRT (which is empty here).

**Comment by PE5PVB** [comment]
That's because signallevel drops below low level offset
