### ISSUE TITLE
PI-Code is blinking before ID is shown

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#389]
I've tested USA settings (although our PI-Codes here in Europe cannot be easily transferred into US-American IDs) and realized that the PI-Code has a very interesting display behavior (seems like blinking or re-printed) as long as the ID is being calculated.

[VID_20231103_204919.webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/96dcd400-ad68-4d44-9cba-b3a8b62e9c77)

**Comment by PE5PVB** [comment]
Fixed.

**Comment by andimik** [comment]
https://github.com/PE5PVB/TEF6686_ESP32/commit/5d86568f486c1853925bfa78e9d352e019922957

Therefore closing.
