### ISSUE TITLE
No battery info show when WIFI is on

### ISSUE THREAD

**Issue by TuxTiger** [PE5PVB/TEF6686_ESP32#390]
Like the descritption says, images:

![image](https://github.com/PE5PVB/TEF6686_ESP32/assets/4631482/4f32bd12-86c6-4142-8299-0d22771a925e)

![image](https://github.com/PE5PVB/TEF6686_ESP32/assets/4631482/79c8afba-7459-47cb-8517-944d684198ce)

Build 1030.2141

**Comment by HyperDX** [comment]
I think that was a hardware limitation because the same pins are used for WiFi and battery voltage measurements.

**Comment by PE5PVB** [comment]
Correct. Hardware won't allow you to have both at the same time.
