### ISSUE TITLE
EON page always complains about no EON and no AF

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#413]
The new EON page always prints two wrong messages when you toggle with the MODE button.

EON stations will even get the message `No EON available`, but on the next page EON is displayed.
Same with AF: The message says, `No AF available`, but one second later you see AF.

I guess there is a timing issue or the text always appears by mistake.

Tested with 2eac470

[VID_20231114_215529.webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/f4e5b8f9-662f-4eb9-a487-577cd97693d4)

**Comment by PE5PVB** [comment]
Fixed.

**Comment by andimik** [comment]
I have not tested the fix, but the source code makes sense for me.
