### ISSUE TITLE
Add PTY to EON screen as decimal value

### ISSUE THREAD

**Issue by lxsxl** [PE5PVB/TEF6686_ESP32#414]
Just not to forget I add this as an own issue, hope it's okay that way.

**Comment by andimik** [comment]
Is this really an issue??

**Comment by PE5PVB** [comment]
Done.

**Comment by andimik** [comment]
Now it's an issue :-)

The PTY value gets lost when you leave that menu to AF and enter again to EON. It will never come back for the actual frequency. You need to retune to another frequency. Going back to advanced RDS view and enter AF/EON will not help.

[VID_20231115_204830.webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/54d7e6af-111e-4a87-84b9-267eb98ae650)

**Comment by PE5PVB** [comment]
Fixed ;-)

**Comment by andimik** [comment]
Yes, confirmed, fixed in 17f30d8

Please close the issue.
