### ISSUE TITLE
The 99th memory cell, after each switching off and turning on of the receiver, is reset and shows 0.00

### ISSUE THREAD

**Issue by Yurij20** [PE5PVB/TEF6686_ESP32#423]
The 99th memory cell, after each switching off and turning on of the receiver, is reset and shows 0.00
https://youtu.be/WpjTd3Cns5E?si=4K_qbFnN7UCzUHye

**Comment by PE5PVB** [comment]
Fixed.

**Comment by Yurij20** [comment]
fixed, thanks)
