### ISSUE TITLE
Glitches on EON-PS

### ISSUE THREAD

**Issue by lxsxl** [PE5PVB/TEF6686_ESP32#432]
Glitches may appear on EON-AF underscores when a peviously received code get‘s lost:
![IMG_8563](https://github.com/PE5PVB/TEF6686_ESP32/assets/140750201/27ac48ca-f6b7-442d-b6a7-d8dc2c4b5e59)

**Comment by andimik** [comment]
Yes, I have the same issue.

**Comment by PE5PVB** [comment]
It shouldn't show underscores in EON viewer, so I removed that function.

**Comment by lxsxl** [comment]
Can you use an alternative character so that the blanks are still "visible"? Maybe a dot in the middle?

**Comment by PE5PVB** [comment]
Currently not. This will have to much impact now.

**Comment by lxsxl** [comment]
Okay, then I will close for now.
