### ISSUE TITLE
Primary colour in case of RDS loss

### ISSUE THREAD

**Issue by lxsxl** [PE5PVB/TEF6686_ESP32#434]
If RDS get's lost and you return from AF/EON-screens to advanced RDS-screen PS, PI and PTY will be in primary colour for a few milliseconds and then switch to secondary colour.

**Comment by andimik** [comment]
At what stage RDS needs to get lost? 

Because I tried but could not get what your are writing.

**Comment by andimik** [comment]
Ah, when signal gets lost and switching 2x from normal to advanced and AF view and back will print PS and PI in yellow, but the rest in blue. You are right, the colors are wrong then.

**Comment by PE5PVB** [comment]
Fixed.

**Comment by lxsxl** [comment]
I close the issue as completed.

**Comment by andimik** [comment]
No, PTYN will stay in yellow. Please reopen it.

**Comment by andimik** [comment]
No, PTYN is still in wrong color. Seems in https://github.com/PE5PVB/TEF6686_ESP32/commit/c2d89bab245419871dbb8b7d6bc2646f033876b7 there is no fix for ptynold

![IMG_20231122_204712](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/cd6c81f1-a730-4c40-b169-3d8b9a19f67a)

What about ECC/LIC/PIN color?
