### ISSUE TITLE
MPX output broken

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#440]
Between 15th Nov 

![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/e018902e-1bdc-4b14-8b7a-b8ea7b7aa795)

and 19th Nov 

![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/e8782028-8885-4800-9b96-8ddf93f5b22e)

the mpx output got broken.

**Comment by PE5PVB** [comment]
I just tested it, no problems here. Which chip version do you have V102 or V205?

**Comment by andimik** [comment]
I'm just testing various TEFs and versions. No idea if this is hardware-related ...

**Comment by PE5PVB** [comment]
Note, only one channel has MPX, the other one has filtered mono output.

**Comment by andimik** [comment]
I need to re-solder the headphone output, seems the connection is broken. My fault.
