### ISSUE TITLE
Glitches in Advanced RDS in RT

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#442]
I cannot explain what kind of "ghost" lines are displayed here.

This is an older record, but my TEFs will show them, so not related to one specific display.

[VID_20231122_211619.webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/837c9a32-ceff-4daa-b7f8-6bb891776c17)

http://andimik.bplaced.net/temp/rds_slovenia_prvi_spec_char_date_change_mpx.wav

**Comment by PE5PVB** [comment]
Yes, I can't fix this. This has to do with the font. What you see is the top of a high char like Ó. But if I make this smaller it will kill characters like g.

**Comment by andimik** [comment]
I will check if the letter is `Ç`
