### ISSUE TITLE
RDS error indicators not updated on RDS loss

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#453]
My expectation is that (all) the dots get red when RDS is lost. In fact, they might stay (all or partly) green, see attached video.

[VID_20231127_205138.webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/b8aead14-6549-4424-9d2d-e905cbdcfb5d)

**Comment by PE5PVB** [comment]
Fixed.

**Comment by andimik** [comment]
https://github.com/PE5PVB/TEF6686_ESP32/commit/b6f0ae24fc230a945f80b8b6b928ed8e955a3a78

Yes fixed.

Closing.
