### ISSUE TITLE
PI-Code in RDBS wrong color

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#454]
See https://discord.com/channels/1053804249651359765/1080501413651693578/1179480204696109056

![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/3dd1d129-3358-4358-89e7-f5b44c6b6d86)

Setting to American RDBS, the PI Code is displayed in blue instead of yellow. In advanced RDS view it's ok.

I guess this is an issue, although I am from Europe.

**Comment by PE5PVB** [comment]
Fixed.
