### ISSUE TITLE
Can't save frequency 87.5 FM to memory

### ISSUE THREAD

**Issue by Yurij20** [PE5PVB/TEF6686_ESP32#456]
Can't save frequency 87.5 FM to memory.  Instead of saving, the memory cell is hidden and its number is shown in green

**Comment by Overland-DX** [comment]
I can confirm the issue here as well.
On the other hand, there is a good opportunity to reset a memory slot.

**Comment by ohmytime** [comment]
This is the default channel value, I will change it to other values

**Comment by ohmytime** [comment]
I just fixed this issue #458 ,please test.

**Comment by PE5PVB** [comment]
This whole issue will be fixed in a future release when we add a skip function for memory channels.

**Comment by ohmytime** [comment]
> This whole issue will be fixed in a future release when we add a skip function for memory channels.

Now , my solution can't save FM 108.00 to channel (smile)

**Comment by Overland-DX** [comment]
Can't you just change the value to an invalid value? 
Since empty memory slots are not tunable anymore anyway?

#define EE_PRESETS_FREQUENCY 10800  --> #define EE_PRESETS_FREQUENCY 00000

I think I've tested that value before, but can test again when I get the Arduino IDE installed again.

**Comment by Overland-DX** [comment]
@ohmytime 
I have tested the value 00000 for a few days without finding any bugs. But there is probably a better solution.

**Comment by PE5PVB** [comment]
Where did you change that value?

**Comment by andimik** [comment]
EE_PRESETS_FREQUENCY, see above

**Comment by Overland-DX** [comment]
> Where did you change that value?

In constants.h, Line 194: #define EE_PRESETS_FREQUENCY        00000

**Comment by PE5PVB** [comment]
Thanks. I changed the value on constants.h

**Comment by Yurij20** [comment]
Fixed. Thanks 😊
