### ISSUE TITLE
Mute icon issue

### ISSUE THREAD

**Issue by Mike86-CZE** [PE5PVB/TEF6686_ESP32#466]
When I manually stop the auto scan, the mute icon remains displayed.

**Comment by PE5PVB** [comment]
I can't reproduce this. Can you guide me step by step?

**Comment by Mike86-CZE** [comment]
Switch the radio to SW or OIRT range.  This is because there will be enough time to manually stop the scan.  Set the tuning mode to AUTO and turn the tuning knob to start scanning.  Before the tuning stops by itself at a certain frequency, press the bandwidth button or the MAN/AUTO/MEM selection button.  Tuning stops, sound is activated, but the mute icon remains displayed.

**Comment by PE5PVB** [comment]
Fixed
