### ISSUE TITLE
Automatic activation of underscores

### ISSUE THREAD

**Issue by Mike86-CZE** [PE5PVB/TEF6686_ESP32#468]
If I have the option "Show RDS errors" set to "All" and I tune in to a frequency with a high error rate, after a while the option "Show underscore in RDS" is activated by itself, which can no longer be deactivated in the settings.

https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/ac87b9fd-90e1-4ae7-9627-944e0f75966a

**Comment by PE5PVB** [comment]
I have no idea what causes this, I can't reproduce it and I don't see any way in the firmware which can cause this.

**Comment by Mike86-CZE** [comment]
Note that the error only occurs when almost all the dots are red.  In addition to the underscores, the "Show PI errors" function is also activated, which cannot be deactivated either.

https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/9ee09d95-a1be-475b-a2de-03e051401594

**Comment by Mike86-CZE** [comment]
I am updating the list of all RDS settings, which are then blocked and cannot be changed.
Show underscore in RDS
RDS filter
Show PI errors
RT buffering
Auto sort AF
Fast PS

**Comment by PE5PVB** [comment]
It looks like a glitch in the memory somewhere. Will be very difficult to find.

**Comment by PE5PVB** [comment]
I moved the variable in the code to another struct. It seems to be caused by a memory leak. Since the software is that complex I have no way of finding it. Maybe this did the trick.

**Comment by Mike86-CZE** [comment]
The issue was partially resolved in version 2.00.6.  The underscores are no longer activated, but the "RDS filter", "Show PI errors", "RT buffering", "Auto sort AF" and "Fast PS" settings are still frozen (cannot be changed).

**Comment by PE5PVB** [comment]
Can someone confirm this?

**Comment by andimik** [comment]
I personally see no reason why someone should use "Show RDS errors = all" (as this generates too much issues), so I will not test that, sorry.

**Comment by PE5PVB** [comment]
Yes, I agree with you. Setting to showing all errors just doesn't make sense.
