### ISSUE TITLE
FM band cannot receive radio station

### ISSUE THREAD

**Issue by LYMarvin** [PE5PVB/TEF6686_ESP32#474]
There are two troubles here:
1.FM band cannot receive radio station,no issues with other bands(including OIRT);

2.Long press the MODE key to enter the menu and crash (the shuttle and all buttons fail).

How to solve it.Thank you!
SMETERPIN not used,BANDBUTTON  defined PIN 27(if define PIN 4,Stuck startup).
![01-MW OK](https://github.com/PE5PVB/TEF6686_ESP32/assets/56508774/8143d819-65c3-45fe-802f-819e8a4bc5f3)
![02-SW OK](https://github.com/PE5PVB/TEF6686_ESP32/assets/56508774/f25425de-7847-4755-98a4-ad8f744705fe)
![03-OIRT OK](https://github.com/PE5PVB/TEF6686_ESP32/assets/56508774/3f537c18-e3ff-4873-b89e-b5630bb28491)
![04-FM not work](https://github.com/PE5PVB/TEF6686_ESP32/assets/56508774/dbe1eb6f-cfa8-4716-bdec-04f609bd1a62)
![05-menu not work](https://github.com/PE5PVB/TEF6686_ESP32/assets/56508774/b4d78f28-c81e-43cd-8fb2-d77789977b7e)
![06-Stuck startup](https://github.com/PE5PVB/TEF6686_ESP32/assets/56508774/f8cc3de1-e9cf-4a49-a0f2-afb2289e6144)

**Comment by PE5PVB** [comment]
Looks like a hardware problem on your ESP32. This is not a softwareproblem. Please refer to Discord for this kind of questions.
