### ISSUE TITLE
Another problem with the segment font

### ISSUE THREAD

**Issue by leryfm** [PE5PVB/TEF6686_ESP32#498]
Hello Sjef!
 
Why the segment font has been changed again in the latest firmware 2.00.6?
I suspect that the goal was to make it closer to what it was before August 2023, but believe me, the one from January 2024 is much better. 

The numbers are more correct in shape and more beautiful. Please return it. For what reason can you not make two variants? "Classic" / "Classic 2", both of them are on the list if you found the opportunity to return the old one? (at the same time, it still does not have 100% similarity with the one that was)
To be honest, I felt disappointed again, just like when the segment font disappeared completely. Moreover, the rest of the fonts were not affected; this is clearly not a return to the old library or its replacement with another new one. I’m not insisting on anything, but I would like to know why this particular font needed to be changed again, because this is an important point that I asked about earlier... 

Thank you for any answer. I hope that two of these fonts can be saved, if someone needs a second option that replaced the previous one.
But I really wouldn’t like to stay on the old firmware... This is a very important point

**Comment by alexstarvrn** [comment]
I support it, the font that was in the previous firmware in January looked better. Please return it.

**Comment by Yurij20** [comment]
I support it, the Classic font has unfortunately become worse in appearance, some segments have begun to look uneven

**Comment by PE5PVB** [comment]
Font has been changed for the last time.

**Comment by Yurij20** [comment]
I checked the classic font and it became much better, but the middle segment in numbers is still too long and doesn’t look very good.  If it is possible to shorten this middle segment and sharpen the lateral vertical segments of the central one in the center?) In the photo I carefully showed how) Thank you).  In the Motoya font, if you look closely, the numbers in height have become uneven, if you look closely, it’s insignificant, but it’s there.  At 2.00.6 everything was perfect.  I would return it as in 2.00.6
![Uploading 20240301_121948.jpg…]()

**Comment by PE5PVB** [comment]
No photo...

**Comment by Yurij20** [comment]
![Uploading 20240301_121948.jpg…]()

**Comment by Yurij20** [comment]
https://disk.yandex.ru/i/cO6F81ktYzvVAw

I uploaded the disk through Yandex, but it doesn’t directly upload to Github

**Comment by andimik** [comment]
@Yurij20

You need to wait till the upload was successfully and then submit.

**Comment by Yurij20** [comment]
![20240301_121948](https://github.com/PE5PVB/TEF6686_ESP32/assets/141682122/508080bc-126f-4ffa-b2f0-a61ecbc84769)

**Comment by leryfm** [comment]
Dear Sjef! 

Please return the font that was presented in the firmware at the beginning of January 2024. 
It was the most beautiful, better than all the previous ones. It was a real New Year's gift for me, very nice, and now it has disappeared again. 
I don't understand why it needed to be changed and removed again. 
Perhaps it was necessary to replace the library again, but all other fonts added with the new library were not touched. 
Why can’t you **leave both versions of the segment font** if you don’t like the one in the photo and want to change it? I kindly ask you to return the font and not remove or modify it.

![font](https://github.com/PE5PVB/TEF6686_ESP32/assets/150333458/b8c69ff4-8190-419b-9043-556308cceb06)

**Comment by PE5PVB** [comment]
We will do some small adjustments to the classic font and added a modern 8-digit font extra. And there we draw a line. If you want to do more adjustments, you are welcome to do it yourself.

**Comment by leryfm** [comment]
Thank you for your reply. Did I understand you correctly that the font with which I attached a photo above will be returned? Or are we talking about something else called "modern 8-digit font extra"?

I would like to clarify: Just bring back that segmented font that was in January '2024. Exactly that one, without changing or correcting anything. It doesn't need fixing, smoothing etc. Just like it was in beta 2.00.3 and so on, and then for unknown reason it disappeared. I'm talking about the font in the photo I sent above. It's great and I even wrote you a happy review...

It’s a strange decision to remove it after that without explanation....
“Do it yourself” is an easy answer, but I don’t understand why this font doesn’t deserve to be present in the main branch of the firmware along with the others, especially if it was already there, and it's the best!

**Comment by zygmund2000** [comment]
Btw adjusting anti-aliased fonts is very difficult, the processing tool does it very very poorly. For me it is pain in the eyes and I would really like to get rid of the small smoothed fonts.
If anyone knows an alternative method to generate it, please let me know
