### ISSUE TITLE
Complilation from src

### ISSUE THREAD

**Issue by zygmund2000** [PE5PVB/TEF6686_ESP32#5]
Hi
I'm trying to compile it from sources but I have to many errors, can u help me with this? I'm using Arduiono IDE and all libraries seems to look ok
Thanx

**Comment by HyperDX** [comment]
Make sure you are using the latest ESP32 board definition. You can update in in your Arduino's board manager. If you use old v1.x you can get errors related to AnalogWrite which wasn't included in older versions but it is in the newest.

**Comment by zygmund2000** [comment]
Finally I done it without error and it works, but how to set compilator to make single binary file?
Also I need some help to find in code how to change font of frequency.
BTW imo encoder now is too smooth, and dynamic radio text sometimes freeze, back to normal after retune station.
