### ISSUE TITLE
Signal level changed

### ISSUE THREAD

**Issue by zygmund2000** [PE5PVB/TEF6686_ESP32#503]
Hi,
In actual version signal level is different then older versions and is about 4db lower, eg. 70dBuV now is 66 and AGC settings doesn't change it. I didn't try to compare lower or higher values so maybe impact of changes is more specific.
Please look at it.

**Comment by PE5PVB** [comment]
Could be. AGC only kicks in on very high signal levels. And it's all about signal to noise ratio.

**Comment by zygmund2000** [comment]
I meant that it was possible to set the AGC as it was before for compatibility because signal values is for me important, that change breaks my statistics.

**Comment by andimik** [comment]
If you rely on the value, you should not update the software ;-)

**Comment by PE5PVB** [comment]
The default value of AGC (which was set fixed in the past) is 92dBuV. I just found an error in setting the AGC. Should be fixed now in the repository.

**Comment by zygmund2000** [comment]
I can confirm that it seems to be fine now.
Thx
