### ISSUE TITLE
RT will only be cleared at 2nd frequency change

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#509]
Tested with d96a2e576adf135f9025944ad332841494d2444f , the RT will not be cleared when you change the frequency (for instance +100 kHz), you need to tune again (for instance +200 kHz) in order to let it disappear.

[VID_20240315_215208.webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/988e962d-bbf3-4bc9-befb-0c371c3c61bf)

**Comment by PE5PVB** [comment]
Fixed

**Comment by andimik** [comment]
confirmed, tested with 44bab28043ae87ef17fc1ac3e7a74b9b39927f21 from today.
