### ISSUE TITLE
switch encoder standard/optical not working correctly

### ISSUE THREAD

**Issue by Mike86-CZE** [PE5PVB/TEF6686_ESP32#511]
After updating to 2.00.9 (I skipped 2.00.8) the encoder settings have no effect.  In both cases, when rotated, the frequency sometimes jumps two positions (e.g. 200 kHz instead of 100 kHz)

**Comment by PE5PVB** [comment]
Was this not the case in previous versions?

**Comment by Mike86-CZE** [comment]
in version 2.00.7 and earlier I did not encounter this problem. It was happened with the "optical" setting, but it was fine with the "standard" setting.

**Comment by PE5PVB** [comment]
OK. I did replace the version about half an hour after releasing it via Discord. Can you try to update it again to make sure if the problem is still there, because I changed something there.

**Comment by Mike86-CZE** [comment]
I downloaded it today.  was inserted on 14.3. 2024 20:10.  So I should really have the current version.

**Comment by PE5PVB** [comment]
Ah ok. I will fully revert this change because of debouncing of some cheap rotary encoders.

**Comment by PE5PVB** [comment]
Fixed
