### ISSUE TITLE
comm frequency outputs are somtimes missing newlines and sometimes off by factor 1/10

### ISSUE THREAD

**Issue by clorenz** [PE5PVB/TEF6686_ESP32#521]
In TEF6686_ESP32.ino, several times, the newline after a frequency output is missing,
and in src/comms.cpp on one occurrency, the frequency is off by a factor of 1/10  (9990 instead of 99900).

I'd have a pull request (locally tested), but I have no permission to upload a branch and set the pull request.

**Comment by PE5PVB** [comment]
I added you to the project. Please try again.
