### ISSUE TITLE
PI code will be printed in bold after RDS return

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#522]
When the signal got bad (blue font) and RDS came back (yellow font), the PI code looks like printed in bold.

[VID_20240403_195514[1].webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/f46a75d0-18be-4f08-8835-8ce3f8c2ca7b)

**Comment by PE5PVB** [comment]
Fixed.

**Comment by PE5PVB** [comment]
Please confirm if the problem has been solved.

**Comment by andimik** [comment]
yes, fixed
