### ISSUE TITLE
Battery voltage meter problem

### ISSUE THREAD

**Issue by Mike86-CZE** [PE5PVB/TEF6686_ESP32#529]
The battery voltage meter sometimes shows an incorrect value.  Like now, it was showing 3.6V.  I turned the TEF off and on again and it shows the correct 3.9V.  With the new version 2.00.13 this has happened to me several times already.

**Comment by PE5PVB** [comment]
Please check again with v2.00.13b

**Comment by Mike86-CZE** [comment]
Unfortunately, this is the second time this has happened to me, even with a newer version.

**Comment by PE5PVB** [comment]
Please note that the voltage readout will always be a bit buggy, because it's implemented in the hardware the wrong way.

**Comment by Mike86-CZE** [comment]
Something must have changed in the last versions.  Now fully charged battery shows as 64% / 3.75V.  Previously, the charge was displayed quite accurately.

**Comment by PE5PVB** [comment]
Yes, I already undo this change.
