### ISSUE TITLE
Screensaver in Advanced RDS view does not work

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#533]
Seems the screensaver only works in the main screen. But when I am in advanced RDS view, it does not work.

**Comment by PE5PVB** [comment]
@ohmytime Can you take a look at this?

**Comment by ohmytime** [comment]
After some digging, I found that the original design was to disable the screensaver on the Advanced RDS page. 
So, what kind of function is needed now?

![image](https://github.com/PE5PVB/TEF6686_ESP32/assets/490477/d6194c96-fcc9-4802-8fdc-4d686f37b9f5)

<img width="262" alt="image" src="https://github.com/PE5PVB/TEF6686_ESP32/assets/490477/b8ce0de9-61f7-4ee6-a390-038cbe1d900a">

**Comment by PE5PVB** [comment]
@ohmytime Please enable screensaver in all screens except menu.

**Comment by ohmytime** [comment]
OK

**Comment by PE5PVB** [comment]
Fixed.

**Comment by PE5PVB** [comment]
@andimik Can you confirm, so we can close this one?

**Comment by andimik** [comment]
Yes, it works now in all menus.
