### ISSUE TITLE
Tickers are slow

### ISSUE THREAD

**Issue by lxsxl** [PE5PVB/TEF6686_ESP32#540]
Actually it seems that the tickers have slowed down again (mainly in advanced RDS view)

**Comment by andimik** [comment]
Sometimes tickers take a short break:

[VID_20240423_203720.webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/b0ebf457-9b6a-4b8a-ad3d-5b2b3a0d7b69)

**Comment by PE5PVB** [comment]
Tickers are called in a loop. When there are more things to do in this loop, or the radio is waiting for data from the chip the tickers can slow down or stutter. Nothing to do about that.
