### ISSUE TITLE
No AlertReady Test except Ontario (Canada only)

### ISSUE THREAD

**Issue by Alexander-Burns** [PE5PVB/TEF6686_ESP32#554]
No AlertReady Test in Country Music except Ontario, partial test in Canada. See audio recording in non-TEF6686_ESP32 devices.
[screen-capture.webm](https://github.com/PE5PVB/TEF6686_ESP32/assets/113866683/34804509-6121-49bf-a05a-b4fddcc47ca0)

**Comment by PE5PVB** [comment]
What is your question?

**Comment by Alexander-Burns** [comment]
Can you call me now?

**Comment by Alexander-Burns** [comment]
Awesome, thanks for the update!

**Comment by Alexander-Burns** [comment]
Duplicate of https://github.com/PE5PVB/TEF6686_ESP32/issues/554
