### ISSUE TITLE
Auto squelch is activated by default on silver TEFs with no squelch knob, cannot be deactivated. AM tuning issue.

### ISSUE THREAD

**Issue by MCelliotG** [PE5PVB/TEF6686_ESP32#556]
Two issues I encountered with the latest beta.
1. The silver TEFs that have no squelch knob now have squelch activated by default and the option to deactivate is not available. Perhaps it would be better to set default squelch value to off, to support these models as well.
2. The tuning cycle on AM band is broken. When the tuning reaches the end of the band (1791 khz) and returns to 522 khz it blocks and the tuning knob cannot tune the frequencies upwards, only downwards. The only way to reactivate the knob tuning upwards is to manually select the frequency, but when the tuning reaches the end of the band it blocks again. I could make a video with the issue.

**Comment by PE5PVB** [comment]
1.  Please do a factory reset.
2.  Fixed.

**Comment by MCelliotG** [comment]
Factory reset fixes the first issue but it defaults the menus to Chinese. This should be considered as well.

**Comment by PE5PVB** [comment]
Check the file config.h if the line #define CHINA_PORTABLE is remarked.

**Comment by ohmytime** [comment]
> Factory reset fixes the first issue but it defaults the menus to Chinese. This should be considered as well.

I'm considering reverting to the previously selected language when doing a factory reset.

**Comment by PE5PVB** [comment]
> > Factory reset fixes the first issue but it defaults the menus to Chinese. This should be considered as well.
> 
> I'm considering reverting to the previously selected language when doing a factory reset.

Well, default language after a reset should just be English. Default settings call should set all eeprom values to a designated value. No recovery.

**Comment by ohmytime** [comment]
> > > Factory reset fixes the first issue but it defaults the menus to Chinese. This should be considered as well.
> > 
> > 
> > I'm considering reverting to the previously selected language when doing a factory reset.
> 
> Well, default language after a reset should just be English. Default settings call should set all eeprom values to a designated value. No recovery.

Well we can make it the second parameter of function DefaultSettings, 
```
void DefaultSettings(byte userhardwaremodel, byte nowlanguage)

```
So that we can recall user pre-selected language.

**Comment by ohmytime** [comment]
Think about this case:
User selected Italian as his display language, and then he made a factory reset.
If the default language is English ,it is okay, but I think italian would be better.

**Comment by andimik** [comment]
Better than Chinese for sure.

**Comment by PE5PVB** [comment]
> Think about this case: User selected Italian as his display language, and then he made a factory reset. If the default language is English ,it is okay, but I think italian would be better.

And what if a user set a foreign language by accident and has no way how to find the language setting?

**Comment by ohmytime** [comment]
> > Think about this case: User selected Italian as his display language, and then he made a factory reset. If the default language is English ,it is okay, but I think italian would be better.
> 
> And what if a user set a foreign language by accident and has no way how to find the language setting?

> > Think about this case: User selected Italian as his display language, and then he made a factory reset. If the default language is English ,it is okay, but I think italian would be better.
> 
> And what if a user set a foreign language by accident and has no way how to find the language setting?

The needs does exist.

BTW, do we need to, for example, make a detailed breakdown of restoring factory settings?

ALL(default to English)
User Settings + Preset stations
User Settings only 

It's probably better to do it on the menu,  as a user's choice
