### ISSUE TITLE
Small holes in RDS quality indicator bars?

### ISSUE THREAD

**Issue by SpiderBlocker** [PE5PVB/TEF6686_ESP32#582]
![20240528_192718](https://github.com/PE5PVB/TEF6686_ESP32/assets/139555167/76e93492-e483-4699-a8ab-ce42fa9ab922)
Not really a big issue, but I have been wondering why the green RDS quality indicator bars on the main screen must have these small holes to them?

**Comment by PE5PVB** [comment]
Checked it. But maybe it's a display thing. I can't reproduce it on my radio. Nothing to do about it. It looks kinda cool ;-)

**Comment by PE5PVB** [comment]
Fixed

**Comment by SpiderBlocker** [comment]
Wunder**bar**!

**Comment by lxsxl** [comment]
Almost the same "issue" is in advanced RDS mode (here only the top ends of the bars).

**Comment by SpiderBlocker** [comment]
> Almost the same "issue" is in advanced RDS mode (here only the top ends of the bars).

Indeed, it's there as well. Maybe it is some sort of relic ;-)

**Comment by PE5PVB** [comment]
Did you check out the update from yesterday?

**Comment by SpiderBlocker** [comment]
> Did you check out the update from yesterday?

Yes, it was fixed on the main screen, but not on the advanced RDS screen.

**Comment by SpiderBlocker** [comment]
> Did you check out the update from yesterday?

Main screen was fixed, but its still there on the advanced RDS screen:
![20240601_111128](https://github.com/PE5PVB/TEF6686_ESP32/assets/139555167/ba2bfec1-89f3-496a-a258-a64ed895bc6f)

**Comment by PE5PVB** [comment]
Fixed.

**Comment by lxsxl** [comment]
There is still a little difference in the bars between standard and advanced mode (dropouts in the foots in advanced mode):
![IMG_9461](https://github.com/PE5PVB/TEF6686_ESP32/assets/140750201/b6be4e00-d6d7-4b36-9d86-d4caa1a0b75d)
![IMG_9462](https://github.com/PE5PVB/TEF6686_ESP32/assets/140750201/1342005c-9fad-4fdd-9a76-ac51e370a21a)

**Comment by Yurij20** [comment]
Fixed, thanks)

**Comment by SpiderBlocker** [comment]
RC13, bummerrrszz! Holes are back; both on main screen and advanced RDS. Someone is poking his little drill into them every time!
![20240603_185356](https://github.com/PE5PVB/TEF6686_ESP32/assets/139555167/45c7d0da-8c73-4670-802b-84ca84641ebc)

**Comment by PE5PVB** [comment]
I redesigned this section so only one full bar with rounded corners is written to the screen for each error level step. This will fix this problem once and for all. If it still happens, than your display is faulty ;-)

**Comment by SpiderBlocker** [comment]
Hatseflats, you fixed it again! 
As I am assuming with you that it now has been fixed once & for all, let's close this topic accordingly :-)
