### ISSUE TITLE
The performance of the encoder has deteriorated when rebuilding and switching saved channels.

### ISSUE THREAD

**Issue by Yurij20** [PE5PVB/TEF6686_ESP32#584]
Maybe I just noticed it, but with the generally slow restructuring and switching of saved channels, encoder clicks are often ignored and in any situation the first click is consistently missed with each change in the direction of rotation of the encoder.

**Comment by andimik** [comment]
Seems this is related to hardware. Please clean the Encoder with a specific fluid. I had the same problem.

**Comment by Yurij20** [comment]
> Seems this is related to hardware. Please clean the Encoder with a specific fluid. I had the same problem.

I recently used firmware 1.18, one of the old ones for comparison, in it the encoder works fine on my device. I still have the very first version of the receiver.  For everyone I know who has later releases it works well.  Maybe there is some kind of incompatibility with the first one?

**Comment by andimik** [comment]
Have you tried to use a different model in the settings?

**Comment by Yurij20** [comment]
> Have you tried to use a different model in the settings?

Yes, sure.  I read somewhere on the forums that the problem with skipping occurs due to the autosave mode working in a split second.  If you change it to at least 3 seconds, then the encoder will work much better when adjusted.  Let me remind you once again that the encoder scrolls through the menu perfectly

**Comment by PE5PVB** [comment]
Well, the radio has much to do when switching between memory positions. When you are turning too fast this can end up in not responding. What if you tune preset by preset?

**Comment by Yurij20** [comment]
> Well, the radio has much to do when switching between memory positions. When you are turning too fast this can end up in not responding. What if you tune preset by preset?

Here the situation is such that encoder clicks are ignored not only when switching presets, but during normal settings and mainly when I rotate the encoder quietly.  With fast rotation, relatively everything is better

**Comment by PE5PVB** [comment]
Are you sure you didn't activate optical encoder?

**Comment by Yurij20** [comment]
> Are you sure you didn't activate optical encoder?

switching this optical/standard mode does not make any difference

**Comment by PE5PVB** [comment]
Since v2.00 I've added some extra protection for wear and old rotary encoders, to prevent glitches. Maybe you run into this.

**Comment by Yurij20** [comment]
> Since v2.00 I've added some extra protection for wear and old rotary encoders, to prevent glitches. Maybe you run into this.

Maybe, but here on a forum one friend modified firmware 1.15 and I tested it and the situation was exactly the same with the encoder, I also explained to him about the problem, as he explained to me, this happens due to the minimum autosave threshold after rebuilding the receiver, he raised it to  3 seconds and the problem was solved, the encoder began to work perfectly) Maybe I can try this and maybe it will help you?) If not, I’ll let you know and return everything back and leave everything as is

**Comment by PE5PVB** [comment]
I tried to win some time by not refreshing the whole page when swithcing bands. Maybe this will help you a little. For the rest, I see nothing more to improve right now. If someone have better ideas, please let me know.

**Comment by Yurij20** [comment]
> I tried to win some time by not refreshing the whole page when swithcing bands. Maybe this will help you a little. For the rest, I see nothing more to improve right now. If someone have better ideas, please let me know.

Okay, right now I don’t have my computer handy on a trip, I’ll test the latest update tomorrow.  I remind you that the problem is acute with the encoder adjustment on the very first version of the Chinese receivers.  The menu rotates the encoder perfectly.  Below is a photo of my receiver that I use in the exact series where this problem occurs.  On other later devices everything is relatively good
![20240601_164031](https://github.com/PE5PVB/TEF6686_ESP32/assets/141682122/9c8f2872-0165-4f51-ac48-9176debeb5b6)

**Comment by PE5PVB** [comment]
Maybe in the design with problems they didn't add caps on the rotary encoder to reduce bouncing.

**Comment by Yurij20** [comment]
> Maybe in the design with problems they didn't add caps on the rotary encoder to reduce bouncing.

I checked it now, it’s better with the encoder, it’s faster to change tuning, but there are still clicks being ignored during slow tuning.  Maybe we’ll still try to change the autosave after the adjustment to 3 seconds?)

**Comment by PE5PVB** [comment]
No, that's not causing any delay, only a few uS.

**Comment by Yurij20** [comment]
> No, that's not causing any delay, only a few uS.

ok, then we'll leave it like that.  I see you made adjustments for optical encoders, it helped)
