### ISSUE TITLE
Two more minor thingies

### ISSUE THREAD

**Issue by SpiderBlocker** [PE5PVB/TEF6686_ESP32#586]
- Seems like recently there's some sort of reset going on (short audio mute can be heard) when returning from any of the other pages back to the main screen. If it is intentional, pls ignore.
- Could the RDS-logo be smoothed somehow? To me it is the only dissonant on the otherwise perfect main screen. Otherwise maybe only the textual part of the official logo (EN 50067) could be used?
![RDS-50067](https://github.com/PE5PVB/TEF6686_ESP32/assets/139555167/8a217588-91d3-49a1-817d-73d86f7b4cbf)

**Comment by PE5PVB** [comment]
1.  Yes that is correct. This has to do with a smoother screen refresh.
2.  No not possible by the lack of pixels.
