### ISSUE TITLE
The battery charging indicator began to show incorrectly.

### ISSUE THREAD

**Issue by Yurij20** [PE5PVB/TEF6686_ESP32#587]
I just updated it on the RC12 and the battery indicator began to show 0.35V less than expected.  Also in percentage terms the required amount has fallen.  If, for example, before the firmware it showed 3.92, then with RC12 it shows 3.57.  I return to the old firmware and everything becomes normal

**Comment by PE5PVB** [comment]
Well, 3.92V isn't normal, because it isn't possible, 3.57V is more likely. But again, I undo the patch because people just like to see a higher voltage.

**Comment by Yurij20** [comment]
fixed) thanks
