### ISSUE TITLE
When returning from extended RDS and from the menu to the main screen, a slight stutter appeared and the RDS block began to reset

### ISSUE THREAD

**Issue by Yurij20** [PE5PVB/TEF6686_ESP32#588]
When returning from extended RDS and from the menu to the main screen, a slight stutter appeared and the RDS block began to reset.

**Comment by PE5PVB** [comment]
Yes, stutter is known. Can't change that.

**Comment by Yurij20** [comment]
> Yes, stutter is known. Can't change that.

before rc12 there was no such problem and the RDS block was not reset in this situation

**Comment by PE5PVB** [comment]
Yup. This is the effect of not refreshing the screen on memory change. Sorry.

**Comment by Yurij20** [comment]
> Yup. This is the effect of not refreshing the screen on memory change. Sorry.

I suggest undoing the changes that caused this problem(

**Comment by SpiderBlocker** [comment]
> > Yup. This is the effect of not refreshing the screen on memory change. Sorry.
> 
> I suggest undoing the changes that caused this problem(

I hope a fix would be possible somehow indeed. That stutter has a kind of sloppy feel to it and it wasn't there in the first place.

**Comment by Yurij20** [comment]
> > > Yup. This is the effect of not refreshing the screen on memory change. Sorry.
> > 
> > 
> > I suggest undoing the changes that caused this problem(
> 
> I hope a fix would be possible somehow indeed. That stutter has a kind of sloppy feel to it and it wasn't there in the first place.

Okay, you can put up with the stuttering, at least so that the RDS unit does not reset when returning from the extended RDS

**Comment by PE5PVB** [comment]
Made a workaround for you.
https://github.com/PE5PVB/TEF6686_ESP32/commit/83f2888887de895e52a0f2bdcb02be29ed2606f4

**Comment by Yurij20** [comment]
fixed) thanks
