### ISSUE TITLE
Please make changes to the translation of some PTY positions into Russian:

### ISSUE THREAD

**Issue by Yurij20** [PE5PVB/TEF6686_ESP32#589]
Please make changes to the translation of some PTY positions into Russian:

Varied Speech – Разное
Pop Music – Поп музыка
Rock Music – Рок Музыка
Light Classic M – Легкая классика
Serious Classical – Классика
Other Music – Другая музыка
Children’s Programs – Детские программы
National Music – Национальная музыка
Oldies Music – Музыка ретро

This way these positions are translated more accurately :)

**Comment by andimik** [comment]
What was the source of the existing texts?

**Comment by PE5PVB** [comment]
> What was the source of the existing texts?

Official RDS documentation. But others also found errors in that doc.

**Comment by PE5PVB** [comment]
Done. See: https://github.com/PE5PVB/TEF6686_ESP32/commit/b0332a4de735e128f6f7f5dd47e6cfa2d58f062f

**Comment by Yurij20** [comment]
fixed) thanks
