### ISSUE TITLE
When switching saved stations, the RT line is not cleared until a new RT is found on the one to which you switched. 

### ISSUE THREAD

**Issue by Yurij20** [PE5PVB/TEF6686_ESP32#590]
When switching saved stations, the RT line is not cleared until a new RT is found on the one to which you switched.  Also, a similar situation occurs in the first approximately 10 seconds after turning on the receiver with PTY and with all the flags and parameters in the extended RDS.  And I also noticed earlier that when switching, the oxidation of the RDS unit passes through half a second after switching the memory cell
https://youtu.be/0PfVIvb2gWI?si=jk7OZFexEL76eoha

**Comment by PE5PVB** [comment]
Fixed.

**Comment by numerci** [comment]
Working fine for me after the fix on RC14

**Comment by Yurij20** [comment]
Fixed) thanks)
