### ISSUE TITLE
RC14: Man text partially disabled

### ISSUE THREAD

**Issue by numerci** [PE5PVB/TEF6686_ESP32#595]
1. Select Memory mode
2. Go to the Menu and start a DX Scan with AutoCancel enabled.
3.  Wait till a station is found.
4. The scan stops
Result: The "MAN" text from the main screen remains with a few pixels active. Also the text seem to be duplicated a bit in the upper part.
PS: This is a very, very small bug. Should not be a reason to continue with RC's. Can be fixed in the next releases.

**Comment by PE5PVB** [comment]
Fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/877e92b42d7ed0e15ce1d5781a7770bb08710591
