### ISSUE TITLE
MPX audio output does not switch off audio during scanning

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#596]
This is a long lasting issue, so no fresh bug.

When you are in Advanced RDS view and long press the BW button you come to AF/EON view.

In case the audio output is set to stereo, you get no audio during "SCANNING".

But when the audio output is MPX you hear TEF scrolling through the band, which is not intended, I guess.

**Comment by PE5PVB** [comment]
Fixed.

**Comment by andimik** [comment]
Yes, confirmed. Fixed in 060f8933f79bb5271e68297cfa7a5e18a05b42e9
