### ISSUE TITLE
When Wifi setup failed, show FAILED

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#598]
When Wifi setup failed (wrong password), I expect that FAILED is shown on the display, but it will still show "Connect to ..."

Then you need to restart it but it cannot connect to the Wifi and will disable it of course.

**Comment by PE5PVB** [comment]
Yes, this is a known problem of the current WiFi library. I'm still searching for another one. If I trigger it the way I want it will get in an endless loop. 

Hopefuly I can find a better alternative soon.

**Comment by andimik** [comment]
So this is external software? Then I'll close it of course.
