### ISSUE TITLE
Missing PS in UDP traffic

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#599]
I realized, that PS is not transmitted in UDP (for stationlist):

[udp_traffic.txt](https://github.com/user-attachments/files/15595970/udp_traffic.txt)
[udp_traffic2.txt](https://github.com/user-attachments/files/15595972/udp_traffic2.txt)

The only fields are

- AF
- bandwidth
- ECC
- freq
- PI
- PTY
- Rcvlevel
- RT1

**Comment by PE5PVB** [comment]
Fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/dc2c53ba3a0055407b83752f4b6735b3efae6024

**Comment by andimik** [comment]
Yes confirmed

```
from=TEF_tuner 1;PS=414e54454e4e455f
```

**Comment by andimik** [comment]
BTW: do we really need a space in `from=TEF_tuner 1`?

I can see this space in 5 lines in the `TEF6686_ESP32.ino` file and 6 lines in the `rds.cpp`

Let me propose to delete these spaces. Will test it anyway without, but I guess this will work as well.
