### ISSUE TITLE
OnScreen Battery Indicator not showing any value

### ISSUE THREAD

**Issue by KmanOz** [PE5PVB/TEF6686_ESP32#601]
Battery has been turned on from main menu to show voltage or percentage and shows nothing. Not sure if this is something to do with the Chinese variant I have purchased. I have set the model selector to base.

For reference this is the model I have purchased

https://www.aliexpress.com/item/1005006676689539.html?spm=a2g0o.order_list.order_list_main.16.7d011802H1fE7F

**Comment by andimik** [comment]
Could you add a picture?

**Comment by KmanOz** [comment]
![IMG_2963](https://github.com/PE5PVB/TEF6686_ESP32/assets/1904926/fe0e9993-4def-4e9a-89c7-ea9d8fcdc47e)
![IMG_2961](https://github.com/PE5PVB/TEF6686_ESP32/assets/1904926/ee205a2d-5b71-4c7b-a628-f9b2e17c5eed)

**Comment by PE5PVB** [comment]
You can't show battery level while connecting to WiFi. This is a hardware limitation.

**Comment by andimik** [comment]
@KmanOz 
That's why I asked you to post a picture, so please close it. This is normal behavior.

**Comment by KmanOz** [comment]
Fancy

**Comment by KmanOz** [comment]
No worries cheers

**Comment by PE5PVB** [comment]
Blame the Chinese for choosing a wrong gpio

**Comment by KmanOz** [comment]
Fair enough. I blame them for everything. Nothing against you brother. Keep up the good work.
