### ISSUE TITLE
Storing 'Offset' FM frequencies in memory. 

### ISSUE THREAD

**Issue by Hugh-Glitch** [PE5PVB/TEF6686_ESP32#602]
This helps when a very strong local channel is adjacent. For example DX reception better on 89.38 or 89 39MHz instead of 89.4 with a local 89.5MHz signal.
Can't store them, it jumps to 89.4 if trying to store 89.38.
I think adding a 10KHz option in default FM tuning steps (now 200,100 and 50)would fix it.
Thanks

**Comment by PE5PVB** [comment]
Fixed in b1d83c0

**Comment by Hugh-Glitch** [comment]
Working now, many thanks.
