### ISSUE TITLE
After retuning, the AF still "searches" for another frequency when the screen is off

### ISSUE THREAD

**Issue by Mike86-CZE** [PE5PVB/TEF6686_ESP32#605]
https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/9985d0cf-bcf6-4917-9f5b-e3c6a6a162d7

If I turn off the screen and AF retune to a better frequency, the radio still "searches" every second (corrupts the sound).  when i turn on the screen the problem stops.

**Comment by PE5PVB** [comment]
I think I've fixed this.

**Comment by Mike86-CZE** [comment]
this is how it behaves with RC14.

**Comment by PE5PVB** [comment]
See 6c36b08

**Comment by Mike86-CZE** [comment]
Ok, I will test in the next version.

**Comment by numerci** [comment]
On RC15 for me it works exactly the same as on RC14. Same sound problems when switching the station with the screen off. For me at least there is no change.

**Comment by PE5PVB** [comment]
Fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/58ee9fabee159f7f21d5fb07d670c7c2c3e9cd6a

**Comment by numerci** [comment]
On RC16 it finally works fine. At least for me.

**Comment by Mike86-CZE** [comment]
Now it works properly.  I'm closing this topic.
