### ISSUE TITLE
Some of the Romanian menu entries don't start with capital characters

### ISSUE THREAD

**Issue by numerci** [PE5PVB/TEF6686_ESP32#606]
The following entries in Romanian translation should start with capital characters like the other entries in the menu:

1396    "folosește squelch", // 62    ->    "Folosește squelch", // 62
1401    "ieșire Audio", // 67        ->    "Ieșire Audio", // 67
1432    "unitați S-metru", // 98"    ->    "Unitați S-metru", // 98
1433    "folosești AF", // 99        ->    "Folosești AF", // 99
1510    "porțiune RT", // 176        ->    "Porțiune RT", // 176
1377     "lipsă zgomot FM", // 43    ->    "Lipsă zgomot FM", // 43
1378    "lipsă zgomot AM", // 44    ->    "Lipsă zgomot AM", // 44
1503    "pași MW impliciți", // 169    ->    "Pași MW impliciți", // 169

**Comment by PE5PVB** [comment]
Done in https://github.com/PE5PVB/TEF6686_ESP32/commit/dfa3ed3dbd8dc184944f4d6116d2e9dcdcebcb4f
