### ISSUE TITLE
Repeating a short radiotext

### ISSUE THREAD

**Issue by Mike86-CZE** [PE5PVB/TEF6686_ESP32#609]
If the station does not broadcast a series of spaces after the text in the radiotext and the text is shorter than a line of the screen, the text is unnecessarily repeated and scrolled.

https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/5f4452d2-7600-4db4-892c-59d2c4fba66c

**Comment by Mike86-CZE** [comment]
But now I'm seriously not sure if they started broadcasting the text duplicated... Maybe it would be good to have optional radio text start and end markers?

**Comment by Mike86-CZE** [comment]
No, they really only broadcast the text once.
![Screenshot_20240609-095209_Radio](https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/4791769f-315c-499b-ac58-f11c3c5cd257)

**Comment by numerci** [comment]
Would be possible to also put a screen shot with the RDS settings from the Menu? For me this works fine (for stations transmitting the end of line and also for the ones that do not). There has to be a difference in the settings that could be important.

**Comment by Mike86-CZE** [comment]
![20240609_100927](https://github.com/PE5PVB/TEF6686_ESP32/assets/140615384/6b74b6aa-37ad-48a2-9db8-552847a8a29e)

**Comment by Mike86-CZE** [comment]
It is strange that the radiotext is duplicated on the SONY XDR-S41.  So I'm not really sure how it's broadcast.

**Comment by numerci** [comment]
Thanks.... we have the following differences in the setup:
RDS Filter = ON
Fast PS = OFF
Show clock = OFF
I will give it a try with your setup.
PS: Please note that RDS Filter now works exactly the opposite as before (as designed).

**Comment by numerci** [comment]
Tested with your settings on the stations I have with end of line and without and it works fine. The text is not duplicated for me. It doesn't mean there is no defect just that these settings have no influence.

**Comment by Mike86-CZE** [comment]
On a Samsung Galaxy Mini running Android 2.3.6 with the Spirit app, the radiotext is also displayed twice.  So maybe it's just newer Android that artificially removed the duplication, which confused me.

**Comment by Mike86-CZE** [comment]
So it looks like it's not a bug.  But it would probably be useful to have a tag at the end of the radiotext.  I am closing this issue.

**Comment by PE5PVB** [comment]
Still curious about the RDS data of this station. Can you make a log with RDSSpy or a MPX recording?

**Comment by Mike86-CZE** [comment]
A 192kHz sound card is required for MPX recording, right?

**Comment by andimik** [comment]
Or with SDR#

**Comment by PE5PVB** [comment]
Output of RDSSpy is also ok.

**Comment by Mike86-CZE** [comment]
[fajn927.zip](https://github.com/user-attachments/files/15751600/fajn927.zip)

**Comment by Mike86-CZE** [comment]
> So it looks like it's not a bug. But it would probably be useful to have a tag at the end of the radiotext. I am closing this issue.

A tag is probably not needed.  Just turn on the underscores.

**Comment by andimik** [comment]
The text is already repeated on encoder side

```
andreas@E535:/tmp$ cat ./fajn927.spy | redsea -i hex | grep text
{"pi":"0x2335","group":"2A","radiotext":"FAJN RADIO - PROSTE HITY        FAJN RADIO - PROSTE HITY","prog_type":"Pop music","tp":true}
```

**Comment by andimik** [comment]
![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/f25bfb86-a5c7-4db5-a2d1-55b787876d91)

**Comment by PE5PVB** [comment]
Yup. Nothing to fix here. It's just a crazy engineer.
