### ISSUE TITLE
RC15: when the PS is dynamic the texts are overlapping

### ISSUE THREAD

**Issue by numerci** [PE5PVB/TEF6686_ESP32#613]
1. Select a station with dynamic PS
2. Go to the Advanced RDS window.
3. Press the Band button.
Result: in the AF window the PS is displayed overlapped.

**Comment by PE5PVB** [comment]
Fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/2e614c4c6d62901355626d5441dae258cc9f685e

**Comment by numerci** [comment]
Verified, Works fine now.
