### ISSUE TITLE
Mod meter green to red not aligned evenly with signal meter 

### ISSUE THREAD

**Issue by SpiderBlocker** [PE5PVB/TEF6686_ESP32#614]
I noticed that the mod meter goes from green to red one segment earlier than the signal meter does.
In order to visually line up both meters evenly, I changed the criterion for the mod meter from 53 to 54 (in code line 3293 - 3295) and that works, however I don't know whether that would screw up something else :-)

**Comment by PE5PVB** [comment]
Fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/c2e697d13b367cb5ef5aed4eb0b663cd1c70458c
