### ISSUE TITLE
RDS info disappearing 

### ISSUE THREAD

**Issue by Kurer501** [PE5PVB/TEF6686_ESP32#618]
Would it be possible to get an option to
let RDS info stay? It would be helpful when I use radio for portable DX and use screensaver to save battery. The new little Palm Powerhouse has small battery. 
I almost never use XDRGTK.

**Comment by Yurij20** [comment]
I think yes, you can introduce this feature, but make it disable through the menu.  For me it would be inconvenient

**Comment by PE5PVB** [comment]
Fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/58ea8ec3eee1c6e997da2c0dd36de09650a50dfb

**Comment by Yurij20** [comment]
Fixed, thanks)

**Comment by Kurer501** [comment]
When will the updated version be available for doanload?
