### ISSUE TITLE
A trace of the word "СКАНИРОВАНИЕ" after pi search in the Russian interface language

### ISSUE THREAD

**Issue by Yurij20** [PE5PVB/TEF6686_ESP32#619]
A trace of the word "СКАНИРОВАНИЕ" after pi search in the Russian interface language
![20240627_112705](https://github.com/PE5PVB/TEF6686_ESP32/assets/141682122/9672d8c3-5789-4e8a-9288-82ce6424347a)
.  Please replace the word "СКАНИРОВАНИЕ" in Russian with the word "ПОИСК"

**Comment by PE5PVB** [comment]
I made the word shorter.

**Comment by Yurij20** [comment]
Fixed, thanks)
