### ISSUE TITLE
Squelch is stuck in Auto mode

### ISSUE THREAD

**Issue by Karelski** [PE5PVB/TEF6686_ESP32#621]
After the latest update (2.11), i cannot seem to be able to change squelch settings.
Its stuck in Auto mode and cannot be changed in the Main Settings, pushing any button or turning the tuning knob doesnt change its mode to manual.
This makes listening to weak stations impossible since they get muted.

**Comment by PE5PVB** [comment]
Try a full reset: BW + Rotary during boot.

**Comment by Karelski** [comment]
Yep, that fixed the issue.
Thanks alot

**Comment by PE5PVB** [comment]
Fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/c1a0d0fbd9c15d44e056ed6f865717252a30038c
