### ISSUE TITLE
Add option to switch off AF on memory channels

### ISSUE THREAD

**Issue by numerci** [PE5PVB/TEF6686_ESP32#624]
This AF on memory channels is a very useful features but not one that would be helpful to have always on as not all memory channels have good signal and when it starts it takes time and sometime it finds nothing as there is no alternative frequency.

**Comment by PE5PVB** [comment]
When it's starting to scan you can interrupt it by just tuning a channel up or down.

**Comment by numerci** [comment]
Is true regarding up and down but an action is needed. Maybe someone wants it of... of course can be switched off with the AF option....
