### ISSUE TITLE
comms.cpp line868-869, readInt, Please confirm if it is correct, thanks!

### ISSUE THREAD

**Issue by lvxc88** [PE5PVB/TEF6686_ESP32#626]
comms.cpp

868: VolSet = EEPROM.readInt(EE_BYTE_VOLSET);
869: LowLevelSet = EEPROM.readInt(EE_BYTE_LOWLEVELSET);

I think it should be readbyte, Please confirm if it is correct, thanks!

**Comment by PE5PVB** [comment]
Thanks! Fixed.

**Comment by lvxc88** [comment]
Thank you for your great efforts！
