### ISSUE TITLE
After the first scan in auto search mode, auto search no longer starts and displays this

### ISSUE THREAD

**Issue by Yurij20** [PE5PVB/TEF6686_ESP32#628]
After the first scan in auto search mode, auto search no longer starts and displays this
![20240805_085158](https://github.com/user-attachments/assets/333d9e97-436e-4607-922a-4629258400e7)

**Comment by PE5PVB** [comment]
Yeah, I know, I changed the cancel button to the mode button. See a186e20

**Comment by Yurij20** [comment]
Fixed thanks) Next, I consider it necessary to add a function for auto-sorting memory channels in increasing frequency, manually filling in deleted cells with false phantom frequencies, for example.  Extend the function to all ranges made a choice of which range to scan.  Also make it possible to perform a new auto search without clearing memory channels, but with adding to the remaining free cells) thank you)

**Comment by PE5PVB** [comment]
This can better be done by an external channel editor. I prepared everything for that, but now someone should make a step to write a program. Only thing what I can do is add a option to ignore PI codes which are already in the range.

**Comment by Yurij20** [comment]
> This can better be done by an external channel editor. I prepared everything for that, but now someone should make a step to write a program. Only thing what I can do is add a option to ignore PI codes which are already in the range.

It’s a shame, of course, but other firmware modifications have these functions, if you ever figure out how to do it then do it).  As for the exception when auto-searching for stations with the same pi, this function needs to be disabled.  We have cities where different stations broadcast with the same pi and auto search will not save them all

**Comment by PE5PVB** [comment]
OK. Please open a topic in Discussions and explain how you would like things to work with some examples.
