### ISSUE TITLE
The current frequency is not displayed in the AF list when AF sorting is enabled.

### ISSUE THREAD

**Issue by Yurij20** [PE5PVB/TEF6686_ESP32#635]
I have long wanted to ask about this problem, is it possible to make the current frequency, if it is listed in the AF list of the received radio station, appear in the list also when the AF sorting mode is turned on?

**Comment by PE5PVB** [comment]
Yes, that is done on purpose, because it's logic to have the current frequency in the AF list. It can also cause some issue on other trickmodes.
