### ISSUE TITLE
DX Scan: while it stops on a frequency the update of the screen items is very slow

### ISSUE THREAD

**Issue by numerci** [PE5PVB/TEF6686_ESP32#640]
There seem to be a lag when during a DX Scan it stops on a station. The S-meter is slow, the RDS data updates are slow, the Signal level updates are slow.

Tested on 2.11.4

**Comment by PE5PVB** [comment]
Fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/8834f5f37ff22818fc3f3827892b0f1687db4b01

**Comment by numerci** [comment]
Works fine on 2.11.5. Bug Closed
