### ISSUE TITLE
DX Scan: The Wait time is not actually as set.

### ISSUE THREAD

**Issue by numerci** [PE5PVB/TEF6686_ESP32#646]
1. Set the Waiting time to 20sec
2. Start DX Scan
3. A station is found and after 2 seconds the signal is gone.
Result: The scan resumes immediately. Doesn't wait for the 20 sec added in the Settings.
Expected result: Hold the station for the set period. The signal varies during ES reception... it comes and goes.

**Comment by PE5PVB** [comment]
Fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/19d9fc9f326ea773a44426b9ee1e7b612e8899d0

**Comment by numerci** [comment]
Works fine on 2.11.5. Bug closed.
