### ISSUE TITLE
Translation for NOT POSSIBLE

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#65]
There is still a text which could be localized:

`NOT POSSIBLE` 
in line 1223 and 1226

**Comment by NoobishSVK** [comment]
I would probably change this to "DISCONNECT USB", just like in my fork of the FW as that would tell the users what to do instead.

**Comment by PE5PVB** [comment]
Fixed. Please test and let me know.

**Comment by andimik** [comment]
yes, now it's localized, but once the text has been shown, some pixels below the (former) text become black. For instance half of the letter `M` in `MHz` is now hidden till a restart.

![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/1902173b-1fb5-42c3-bd25-e76f763d8cc0)

**Comment by PE5PVB** [comment]
Ah ok. This has to do with alligning. I'll look into this.

**Comment by PE5PVB** [comment]
I checked this, but can't reproduce the problem.

**Comment by andimik** [comment]
Ok, will try with the latest build tomorrow
