### ISSUE TITLE
Auto Memory stores only 1 station

### ISSUE THREAD

**Issue by numerci** [PE5PVB/TEF6686_ESP32#650]
1. Tune on a local station.
2. Start Auto memory function.
3. Wait for the scan to complete.
Result: only one station is memorized... the one from step 1

Tested on 2.11.4

**Comment by PE5PVB** [comment]
Did this work correct on previous version?

**Comment by numerci** [comment]
From what I remember, yes

**Comment by PE5PVB** [comment]
Fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/6da4c44158ae99a0d99ef359a549211b56a89089

**Comment by numerci** [comment]
Works fine on 2.11.5. Bug closed
