### ISSUE TITLE
Please change the color of the active indicators MAN, AUTO, MEM, AUTO BW, iMS, EQ in the Monochrome theme to white.

### ISSUE THREAD

**Issue by Yurij20** [PE5PVB/TEF6686_ESP32#652]
Please change the color of the active indicators MAN, AUTO, MEM, AUTO BW, iMS, EQ in the Monochrome theme to white.  Gray ones are barely noticeable and inconvenient in daylight hours

**Comment by PE5PVB** [comment]
Done two weeks ago, please check.

**Comment by Yurij20** [comment]
Fixed thanks)
