### ISSUE TITLE
DX Scan and automute equal hold time

### ISSUE THREAD

**Issue by numerci** [PE5PVB/TEF6686_ESP32#654]
Tested on 2.11.5
1. Set the DX scan to Wait time only on signal = OFF
2. Start DX scan
Result: The audio is muted all the time. No matter if any stations is found.
Note: It works fine when Wait time only on signal = ON

**Comment by PE5PVB** [comment]
That is correct, this function is only available when waittime only is switched on.

**Comment by numerci** [comment]
ok, bug report closed.
