### ISSUE TITLE
DX Scan: The Mute sign on main screen always enabled.

### ISSUE THREAD

**Issue by numerci** [PE5PVB/TEF6686_ESP32#655]
2.11.5: During DX Scan even if the scan stops on a station and audio is available the Mute sign on main screen is on,

**Comment by PE5PVB** [comment]
Fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/7d6e89832f82cfaa4aa126bb8e5347598d6695c2

**Comment by numerci** [comment]
Works fine on 2.11.6
Bug closed.
