### ISSUE TITLE
AutoMemory: Prevent double PI from range is not working

### ISSUE THREAD

**Issue by numerci** [PE5PVB/TEF6686_ESP32#656]
On 2.11.5 even if the Prevent double PI is enable (Range) double or triple frequencies with the same PI code are stored.
Note: it works fine using the FULL option.

**Comment by PE5PVB** [comment]
Fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/b16166b2ed36198def3895447a0816e7a30ff422

**Comment by numerci** [comment]
Works fine on 2.11.6. Bug closed.
