### ISSUE TITLE
DX Scan: The audio meter is not working

### ISSUE THREAD

**Issue by numerci** [PE5PVB/TEF6686_ESP32#657]
On 2.11.5 during the DX Scan if the scan is stopping on a station the Audio Meter bar is not displaying anything.

**Comment by PE5PVB** [comment]
Fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/7d6e89832f82cfaa4aa126bb8e5347598d6695c2

**Comment by numerci** [comment]
Works fine on 2.11.6 
Bug closed.
