### ISSUE TITLE
Code compilation problem.

### ISSUE THREAD

**Issue by mi-cha-el-80** [PE5PVB/TEF6686_ESP32#660]
Hello to all forum users.

I am very interested in the project of this radio with the TEF6686 system. I have purchased all the necessary elements for its first implementation, but I have a problem with compiling the code. I have used the available instructions but unfortunately I have not found a solution to my problem.
During compilation an error appears:

C:\Users\Majkel\Documents\Arduino\libraries\libraries\TEF6686_ESP32-main (7)\src\TEF6686_ESP32\TEF6686_ESP32.ino:11:10: fatal error: src/WiFiConnect.h: No such file or directory
11 | #include "src/WiFiConnect.h"
| ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: src/WiFiConnect.h: No such file or directory

Can someone help me solve this problem?
Regards.

![screen 1](https://github.com/user-attachments/assets/a8760376-bb95-4c1a-ab04-e8bc5dda0602)

**Comment by PE5PVB** [comment]
Looks like something goes wrong with the files and subdirectories. Make sure they match Github. So you have the INO file in a subdirectory, and that subdirectory has another subdirectory called src with all the files inside.

**Comment by lvxc88** [comment]
Check if the project folder address is set in the preferences

**Comment by mi-cha-el-80** [comment]
Hello everyone again.

Thank you for your interest in my topic and help. The problem was actually in the file structure where the sketches are stored, by trial and error I managed to solve the problem and go a step further, unfortunately this is not the end of the problems, this time such an error:

Compilation error: too many arguments to function 'hw_timer_t* timerBegin(uint32_t)'

Can I ask for help in solving this problem again?

Thank you.

![screen 2](https://github.com/user-attachments/assets/45842904-0f4c-4a3e-a514-f0c6bad7c15f)

**Comment by PE5PVB** [comment]
Please use latest ESP32 boardmanager v2.x.x

V3 isn't compatible yet
