### ISSUE TITLE
In some languages, the text for "AM AGC" and "AM Antenna gain" in the AM settings menu is reversed

### ISSUE THREAD

**Issue by lvxc88** [PE5PVB/TEF6686_ESP32#664]
In some languages, the text for "AM AGC" and "AM Antenna gain" in the AM settings menu is reversed
Please check and confirm, thank you!

**Comment by PE5PVB** [comment]
Fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/14e6159aeaa4fbc0e4765b674b6968a5d429f8f8

**Comment by lvxc88** [comment]
Resource 36 "AM Antenna gain", unsure if it should be  "AM attenuation"，Please take another look.

**Comment by PE5PVB** [comment]
No it is gain. You can also set a negative value.
