### ISSUE TITLE
Clock displaying in UTC +01:00

### ISSUE THREAD

**Issue by AaronJowitt** [PE5PVB/TEF6686_ESP32#669]
v 2.11.6

**Comment by PE5PVB** [comment]
Please explain

**Comment by AaronJowitt** [comment]
I'm in UTC +10:00. The clock used to display in local time zone with earlier fw versions.

It's currently 06:55 local. 
On a TEF with v2.11.1, clock displays 06:55 (UTC +10:00) . 
On a TEF with v2.11.6, clock displays 22:55 (UTC +01:00).

I've tuned to at least half a dozen stations that broadcast CT (including one that has CT wrong by about 10 minutes), and on all the clock time displayed is in UTC +01:00

**Comment by andimik** [comment]
@kb8u-gqrx

Could you please check your latest commit? 

https://github.com/PE5PVB/TEF6686_ESP32/commit/6acc700968cc0b07b959220f86b8d955148f56a2

**Comment by kb8u** [comment]
Thanks for the explanation.  I found a bug affecting time zones with magnitude greater than 8 hours offset from UTC and have submitted a fix.

**Comment by AaronJowitt** [comment]
Thanks

**Comment by AaronJowitt** [comment]
v2.11.7 does not show a clock here.  
Clock is ON in display settings.

**Comment by kb8u** [comment]
I found a related bug and have submitted a fix.  Sorry I missed this, I have no practical way of testing this since I'm in UTC-4 time zone.

**Comment by AaronJowitt** [comment]
Thanks for the fix.  The clock works in v 2.11.8
