### ISSUE TITLE
Audio mute during Spectral Scan

### ISSUE THREAD

**Issue by numerci** [PE5PVB/TEF6686_ESP32#682]
Would be possible to have the audio muted during the spectral scan? When a spectral scan is done with the Headless the audio is muted while with esp32 firmware there is a strange noise for 1-2 seconds while the scan is executed.

**Comment by PE5PVB** [comment]
Fixed in https://github.com/PE5PVB/TEF6686_ESP32/commit/16bb931175db4cf4f0f9e979dd9a055f01433b20

**Comment by numerci** [comment]
Works well on 2.11.11
