### ISSUE TITLE
Wider capital PS characters overlap EON 

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#70]
Due to larger widths for some capital letters it may happen that PS has a display collision with S/M and EON.

For example in this screenshot
`ANTENNE_` and
`KAERNTEN` 
hide the following text a bit.

![grafik](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/5edee4b0-3872-43ab-8dba-9d9a3c63852b)

**Comment by PE5PVB** [comment]
Yes I know. These flags will be moved to the advanced RDS view.
