### ISSUE TITLE
RT and PS show wrong characters

### ISSUE THREAD

**Issue by andimik** [PE5PVB/TEF6686_ESP32#9]
From June commits on, the PS and RT on the TEF sometimes show wrong characters (even displayed in yellow letters). Till 30th May (1.16RC) it was correct.

See https://github.com/PE5PVB/TEF6686_ESP32/commit/825cc683397269375122b15d9cf8a7f73078f58b

For example the correct PS

> RADIO-K

gets

> RADIO,?

Better to show nothing rather than garbage ...

see screenshots.

![IMG_20230609_161704](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/abcfeb2b-533c-4b54-a544-7b8a7f9f7bbf)
![IMG_20230609_161621](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/5bba14e4-7703-446d-8662-281618a441cd)
![IMG_20230609_161729](https://github.com/PE5PVB/TEF6686_ESP32/assets/24510556/7124cebc-0356-466c-95d1-1c45178537cb)

Testing with latest commit:

```
$ git show
commit f926634f0152cd8c7e7e718ada4cad4aff3522f5 (HEAD -> main, origin/main, origin/HEAD)
Merge: dac00bc e1add2c
Author: Sjef Verhoeven PE5PVB <pe5pvb@het-bar.net>
Date:   Fri Jun 9 12:51:14 2023 +0200
```

**Comment by PE5PVB** [comment]
Will be fixed soon.

**Comment by PE5PVB** [comment]
Closed, see other issue.

**Comment by andimik** [comment]
But this is not fixed yet, you just have closed by mistake, right?

I'm still getting wrong characters.

This is **NOT** related to special characters. I'm talking about ASCII characters and PI-Codes which vary due to bad reception.

**Comment by PE5PVB** [comment]
I know, but there is already a topic on RDS texts
